<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Notebook for Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="stats_files/libs/clipboard/clipboard.min.js"></script>
<script src="stats_files/libs/quarto-html/quarto.js"></script>
<script src="stats_files/libs/quarto-html/popper.min.js"></script>
<script src="stats_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="stats_files/libs/quarto-html/anchor.min.js"></script>
<link href="stats_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="stats_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="stats_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="stats_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="stats_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#about" id="toc-about" class="nav-link active" data-scroll-target="#about">About</a></li>
  <li><a href="#packages-used" id="toc-packages-used" class="nav-link" data-scroll-target="#packages-used">Packages used</a></li>
  <li><a href="#conditional-probability" id="toc-conditional-probability" class="nav-link" data-scroll-target="#conditional-probability">Conditional Probability</a>
  <ul class="collapse">
  <li><a href="#bayes-theorem" id="toc-bayes-theorem" class="nav-link" data-scroll-target="#bayes-theorem">Bayes’ theorem</a></li>
  <li><a href="#bayes-theorem---expaned-version" id="toc-bayes-theorem---expaned-version" class="nav-link" data-scroll-target="#bayes-theorem---expaned-version">Bayes’ theorem - expaned version</a></li>
  <li><a href="#case-study---calculate-churn-rate-for-a-customer-type-with-bayes-theorem-or-something-simplier" id="toc-case-study---calculate-churn-rate-for-a-customer-type-with-bayes-theorem-or-something-simplier" class="nav-link" data-scroll-target="#case-study---calculate-churn-rate-for-a-customer-type-with-bayes-theorem-or-something-simplier">Case study - calculate churn rate for a customer type with Bayes’ theorem (or something simplier)</a></li>
  </ul></li>
  <li><a href="#discrete-probability-distribution" id="toc-discrete-probability-distribution" class="nav-link" data-scroll-target="#discrete-probability-distribution">Discrete Probability Distribution</a>
  <ul class="collapse">
  <li><a href="#binomial-distribtuion" id="toc-binomial-distribtuion" class="nav-link" data-scroll-target="#binomial-distribtuion">Binomial distribtuion</a>
  <ul class="collapse">
  <li><a href="#n-choose-k" id="toc-n-choose-k" class="nav-link" data-scroll-target="#n-choose-k">n-choose-k</a></li>
  <li><a href="#probability-of-each-outcome" id="toc-probability-of-each-outcome" class="nav-link" data-scroll-target="#probability-of-each-outcome">Probability of each outcome</a></li>
  <li><a href="#final-outcome" id="toc-final-outcome" class="nav-link" data-scroll-target="#final-outcome">Final outcome</a></li>
  <li><a href="#wipcase-study-chances-of-customer-make-a-return-to-a-store" id="toc-wipcase-study-chances-of-customer-make-a-return-to-a-store" class="nav-link" data-scroll-target="#wipcase-study-chances-of-customer-make-a-return-to-a-store">(WIP)Case study: chances of customer make a return to a store</a></li>
  </ul></li>
  <li><a href="#poisson-distribution" id="toc-poisson-distribution" class="nav-link" data-scroll-target="#poisson-distribution">Poisson distribution</a>
  <ul class="collapse">
  <li><a href="#poisson-distribution-formula" id="toc-poisson-distribution-formula" class="nav-link" data-scroll-target="#poisson-distribution-formula">Poisson distribution formula</a></li>
  <li><a href="#example-possible-number-of-order-in-a-drive-through-restaurant-wip" id="toc-example-possible-number-of-order-in-a-drive-through-restaurant-wip" class="nav-link" data-scroll-target="#example-possible-number-of-order-in-a-drive-through-restaurant-wip">Example: possible number of order in a drive through restaurant (WIP)</a></li>
  </ul></li>
  <li><a href="#possion-vs-binomial" id="toc-possion-vs-binomial" class="nav-link" data-scroll-target="#possion-vs-binomial">Possion VS Binomial</a></li>
  </ul></li>
  <li><a href="#continuous-probability" id="toc-continuous-probability" class="nav-link" data-scroll-target="#continuous-probability">Continuous Probability</a>
  <ul class="collapse">
  <li><a href="#the-normal-distribution" id="toc-the-normal-distribution" class="nav-link" data-scroll-target="#the-normal-distribution">The normal distribution</a></li>
  <li><a href="#z-score" id="toc-z-score" class="nav-link" data-scroll-target="#z-score">Z-score</a>
  <ul class="collapse">
  <li><a href="#formula---mean" id="toc-formula---mean" class="nav-link" data-scroll-target="#formula---mean">Formula - mean</a></li>
  <li><a href="#formula---proportion" id="toc-formula---proportion" class="nav-link" data-scroll-target="#formula---proportion">Formula - proportion</a></li>
  <li><a href="#python" id="toc-python" class="nav-link" data-scroll-target="#python">Python</a></li>
  </ul></li>
  <li><a href="#smaller-sample-size---t-score-and-t-distribution" id="toc-smaller-sample-size---t-score-and-t-distribution" class="nav-link" data-scroll-target="#smaller-sample-size---t-score-and-t-distribution">Smaller sample size - T-score and T-distribution</a></li>
  </ul></li>
  <li><a href="#sampling-distribution" id="toc-sampling-distribution" class="nav-link" data-scroll-target="#sampling-distribution">Sampling distribution</a>
  <ul class="collapse">
  <li><a href="#standard-error-of-the-mean" id="toc-standard-error-of-the-mean" class="nav-link" data-scroll-target="#standard-error-of-the-mean">Standard Error of the Mean</a></li>
  <li><a href="#the-central-limit-theorem" id="toc-the-central-limit-theorem" class="nav-link" data-scroll-target="#the-central-limit-theorem">The Central Limit Theorem</a></li>
  <li><a href="#standard-error-of-the-proportion" id="toc-standard-error-of-the-proportion" class="nav-link" data-scroll-target="#standard-error-of-the-proportion">Standard Error of the Proportion</a>
  <ul class="collapse">
  <li><a href="#theory-and-formula" id="toc-theory-and-formula" class="nav-link" data-scroll-target="#theory-and-formula">Theory and formula</a></li>
  <li><a href="#case-study-apply-the-standard-error-of-the-proportion-to-churn-rate" id="toc-case-study-apply-the-standard-error-of-the-proportion-to-churn-rate" class="nav-link" data-scroll-target="#case-study-apply-the-standard-error-of-the-proportion-to-churn-rate">Case study: apply the standard error of the proportion to churn rate</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#confidence-level" id="toc-confidence-level" class="nav-link" data-scroll-target="#confidence-level">Confidence level</a>
  <ul class="collapse">
  <li><a href="#interpret-the-confidence-interval" id="toc-interpret-the-confidence-interval" class="nav-link" data-scroll-target="#interpret-the-confidence-interval">Interpret the confidence interval</a></li>
  <li><a href="#incorrect-interpretations" id="toc-incorrect-interpretations" class="nav-link" data-scroll-target="#incorrect-interpretations">Incorrect interpretations</a></li>
  <li><a href="#construct-confidence-interval-for-porportion" id="toc-construct-confidence-interval-for-porportion" class="nav-link" data-scroll-target="#construct-confidence-interval-for-porportion">Construct confidence interval for porportion</a></li>
  <li><a href="#construct-confidence-interval-for-mean" id="toc-construct-confidence-interval-for-mean" class="nav-link" data-scroll-target="#construct-confidence-interval-for-mean">Construct confidence interval for mean</a></li>
  <li><a href="#calculate-confidence-interval-with-scipy" id="toc-calculate-confidence-interval-with-scipy" class="nav-link" data-scroll-target="#calculate-confidence-interval-with-scipy">Calculate confidence interval with SciPy</a></li>
  </ul></li>
  <li><a href="#hypotheses-testing" id="toc-hypotheses-testing" class="nav-link" data-scroll-target="#hypotheses-testing">Hypotheses testing</a>
  <ul class="collapse">
  <li><a href="#steps-for-conducting-a-hypothesis-test" id="toc-steps-for-conducting-a-hypothesis-test" class="nav-link" data-scroll-target="#steps-for-conducting-a-hypothesis-test">Steps for conducting a hypothesis test</a></li>
  <li><a href="#null-vs-alternative-hypothesis" id="toc-null-vs-alternative-hypothesis" class="nav-link" data-scroll-target="#null-vs-alternative-hypothesis">Null VS Alternative hypothesis</a></li>
  <li><a href="#significant-level" id="toc-significant-level" class="nav-link" data-scroll-target="#significant-level">Significant level</a></li>
  <li><a href="#p-value" id="toc-p-value" class="nav-link" data-scroll-target="#p-value">P-value</a></li>
  <li><a href="#examples-of-null-and-alternative-hypothesis" id="toc-examples-of-null-and-alternative-hypothesis" class="nav-link" data-scroll-target="#examples-of-null-and-alternative-hypothesis">Examples of Null and Alternative hypothesis</a>
  <ul class="collapse">
  <li><a href="#example1-mean-weight" id="toc-example1-mean-weight" class="nav-link" data-scroll-target="#example1-mean-weight">Example#1: Mean weight</a></li>
  <li><a href="#example2-mean-height" id="toc-example2-mean-height" class="nav-link" data-scroll-target="#example2-mean-height">Example#2: Mean height</a></li>
  <li><a href="#example3-proportion-of-employees" id="toc-example3-proportion-of-employees" class="nav-link" data-scroll-target="#example3-proportion-of-employees">Example#3: Proportion of employees</a></li>
  </ul></li>
  <li><a href="#type-i-and-type-ii-errors" id="toc-type-i-and-type-ii-errors" class="nav-link" data-scroll-target="#type-i-and-type-ii-errors">Type I and Type II errors</a></li>
  <li><a href="#one-sample-tests---t-test-vs-z-test" id="toc-one-sample-tests---t-test-vs-z-test" class="nav-link" data-scroll-target="#one-sample-tests---t-test-vs-z-test">One sample tests - T-test vs z-test</a>
  <ul class="collapse">
  <li><a href="#one-tail-t-test" id="toc-one-tail-t-test" class="nav-link" data-scroll-target="#one-tail-t-test">One tail t-test</a></li>
  <li><a href="#one-tail-z-test" id="toc-one-tail-z-test" class="nav-link" data-scroll-target="#one-tail-z-test">One tail z-test</a></li>
  </ul></li>
  <li><a href="#calculate-the-p-value-from-a-one-tailtwo-tail-z-score-and-t-score" id="toc-calculate-the-p-value-from-a-one-tailtwo-tail-z-score-and-t-score" class="nav-link" data-scroll-target="#calculate-the-p-value-from-a-one-tailtwo-tail-z-score-and-t-score">Calculate the p-value from a one-tail/two-tail z-score and t-score</a>
  <ul class="collapse">
  <li><a href="#z-score-1" id="toc-z-score-1" class="nav-link" data-scroll-target="#z-score-1">Z-score</a></li>
  <li><a href="#t-score" id="toc-t-score" class="nav-link" data-scroll-target="#t-score">T-score</a></li>
  </ul></li>
  <li><a href="#one-sample-tests---z-test" id="toc-one-sample-tests---z-test" class="nav-link" data-scroll-target="#one-sample-tests---z-test">One sample tests - Z-test</a>
  <ul class="collapse">
  <li><a href="#assumption" id="toc-assumption" class="nav-link" data-scroll-target="#assumption">Assumption:</a></li>
  <li><a href="#case-study-online-delivery" id="toc-case-study-online-delivery" class="nav-link" data-scroll-target="#case-study-online-delivery">Case Study: Online Delivery</a></li>
  </ul></li>
  <li><a href="#two-sample-test" id="toc-two-sample-test" class="nav-link" data-scroll-target="#two-sample-test">Two-sample test</a></li>
  <li><a href="#two-sample-t-test-for-means" id="toc-two-sample-t-test-for-means" class="nav-link" data-scroll-target="#two-sample-t-test-for-means">Two-sample t-test for means</a>
  <ul class="collapse">
  <li><a href="#assumption-1" id="toc-assumption-1" class="nav-link" data-scroll-target="#assumption-1">Assumption</a></li>
  <li><a href="#hypothesis" id="toc-hypothesis" class="nav-link" data-scroll-target="#hypothesis">Hypothesis</a></li>
  <li><a href="#code" id="toc-code" class="nav-link" data-scroll-target="#code">Code</a></li>
  <li><a href="#t-score-for-two-sample-t-test" id="toc-t-score-for-two-sample-t-test" class="nav-link" data-scroll-target="#t-score-for-two-sample-t-test">T-score for two-sample t-test</a></li>
  <li><a href="#get-p-value-from-two-sample-t-test" id="toc-get-p-value-from-two-sample-t-test" class="nav-link" data-scroll-target="#get-p-value-from-two-sample-t-test">Get p-value from two-sample t-test</a></li>
  <li><a href="#case-study---landing-page-ab-test" id="toc-case-study---landing-page-ab-test" class="nav-link" data-scroll-target="#case-study---landing-page-ab-test">Case study - Landing page A/B test</a></li>
  </ul></li>
  <li><a href="#z-test-for-proportion" id="toc-z-test-for-proportion" class="nav-link" data-scroll-target="#z-test-for-proportion">Z-test for proportion</a>
  <ul class="collapse">
  <li><a href="#two-tail-z-test-for-proportion-case-study---customer-satisfaction" id="toc-two-tail-z-test-for-proportion-case-study---customer-satisfaction" class="nav-link" data-scroll-target="#two-tail-z-test-for-proportion-case-study---customer-satisfaction">Two tail z-test for proportion case study - Customer satisfaction</a></li>
  <li><a href="#two-sample-z-test-for-proportion-case-study---employee-satisfaction" id="toc-two-sample-z-test-for-proportion-case-study---employee-satisfaction" class="nav-link" data-scroll-target="#two-sample-z-test-for-proportion-case-study---employee-satisfaction">Two-sample z-test for proportion case study - Employee satisfaction</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear regression</a>
  <ul class="collapse">
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">Simple linear regression</a>
  <ul class="collapse">
  <li><a href="#best-fitted-line" id="toc-best-fitted-line" class="nav-link" data-scroll-target="#best-fitted-line">Best fitted line</a></li>
  <li><a href="#sum-of-squared-residuals-ssr" id="toc-sum-of-squared-residuals-ssr" class="nav-link" data-scroll-target="#sum-of-squared-residuals-ssr">Sum of Squared Residuals (SSR)</a></li>
  <li><a href="#oridnary-least-squares-ols" id="toc-oridnary-least-squares-ols" class="nav-link" data-scroll-target="#oridnary-least-squares-ols">Oridnary Least Squares (OLS)</a></li>
  <li><a href="#correlation-coefficient-r-pearsons-correlation-coefficient" id="toc-correlation-coefficient-r-pearsons-correlation-coefficient" class="nav-link" data-scroll-target="#correlation-coefficient-r-pearsons-correlation-coefficient">Correlation coefficient (r, Pearson’s correlation coefficient)</a></li>
  <li><a href="#model-assumption" id="toc-model-assumption" class="nav-link" data-scroll-target="#model-assumption">Model assumption</a></li>
  <li><a href="#use-logarithm-to-transform-unfit-assumptions" id="toc-use-logarithm-to-transform-unfit-assumptions" class="nav-link" data-scroll-target="#use-logarithm-to-transform-unfit-assumptions">Use logarithm to transform unfit assumptions</a></li>
  <li><a href="#fixing-other-unfit-assumptions" id="toc-fixing-other-unfit-assumptions" class="nav-link" data-scroll-target="#fixing-other-unfit-assumptions">Fixing other unfit assumptions</a></li>
  <li><a href="#run-a-simple-linear-regression-model-in-python-with-the-ols-method" id="toc-run-a-simple-linear-regression-model-in-python-with-the-ols-method" class="nav-link" data-scroll-target="#run-a-simple-linear-regression-model-in-python-with-the-ols-method">Run a simple linear regression model in Python with the OLS method</a></li>
  <li><a href="#evaluate-the-linear-regression-model" id="toc-evaluate-the-linear-regression-model" class="nav-link" data-scroll-target="#evaluate-the-linear-regression-model">Evaluate the linear regression model</a></li>
  </ul></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple linear regression</a></li>
  <li><a href="#advanced-hypothesis-testing" id="toc-advanced-hypothesis-testing" class="nav-link" data-scroll-target="#advanced-hypothesis-testing">Advanced hypothesis testing</a></li>
  </ul></li>
  <li><a href="#logistic-regression" id="toc-logistic-regression" class="nav-link" data-scroll-target="#logistic-regression">Logistic regression</a>
  <ul class="collapse">
  <li><a href="#linear-regression-vs-logistic-regression" id="toc-linear-regression-vs-logistic-regression" class="nav-link" data-scroll-target="#linear-regression-vs-logistic-regression">Linear regression VS Logistic regression</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Notebook for Statistics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="about" class="level1">
<h1>About</h1>
<p>This notebook is for me to record my notes in learning statistics. It includes specific math formulas, examples and how to calculate them in Python. Some notes are directly quoted from various online sources.</p>
</section>
<section id="packages-used" class="level1">
<h1>Packages used</h1>
<div id="8e5ef8a3" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="conditional-probability" class="level1">
<h1>Conditional Probability</h1>
<section id="bayes-theorem" class="level2">
<h2 class="anchored" data-anchor-id="bayes-theorem">Bayes’ theorem</h2>
<p>Bayes’s theorem provides a way to update the probability of an event based on new information about the event.</p>
<p>In Bayesian statistics, prior probability refers to the probability of an event before new data is collected. Posterior probability is the updated probability of an event based on new data. Posterior means occurring after.</p>
<p><span class="math display">\[P(A \mid B) = \frac{ P(B \mid A) * P(A) }{ P(B) }\]</span></p>
<p>Event A = Rain <br> Event B = Cloudy</p>
<p>Now we are trying to get the probaility of A given event B. <br> This means the probability of rain, given it’s cloudy.</p>
<p>This is also called posterior probability.</p>
<p><span class="math display">\[P(Rain \mid Cloud) = \frac{ P(Cloud \mid Rain) * P(Rain) }{ P(Cloudy) }\]</span></p>
<p>Let’s say below are the probability of each event:</p>
<ul>
<li>Overall chance of rain = 10%</li>
<li>All days start off cloudy = 40%</li>
<li>Rainy days start of cloudy (P(Cloud|Rain)) = 50%</li>
</ul>
<p><span class="math display">\[P(Rain \mid Cloud) = \frac{ 50\% * 10\% }{ 40\% }\]</span></p>
<div id="af9139c5" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>p_a_b <span class="op">=</span> <span class="fl">0.5</span><span class="op">*</span><span class="fl">0.1</span><span class="op">/</span><span class="fl">0.4</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(p_a_b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.125</code></pre>
</div>
</div>
<p><span class="math display">\[P(Rain \mid Cloud) = 12.5%\]</span></p>
</section>
<section id="bayes-theorem---expaned-version" class="level2">
<h2 class="anchored" data-anchor-id="bayes-theorem---expaned-version">Bayes’ theorem - expaned version</h2>
<p>Sometimes you don’t know the probability of event B, which is in the denominator of the equation for the basic Bayes’ theorem. In that case, you can use the expanded version of Bayes’ theorem, because you don’t need to know the probability of event B to use the expanded version.</p>
<p><span class="math display">\[P(A \mid B) = \frac{P(B \mid A) * P(A)} {P(B \mid A) * P(A) + P(B \mid not A) * P(not A)}\]</span></p>
<p>Let’s say we are conducting test for a medical condition. Below are the related probability:</p>
<table class="caption-top table">
<caption>Example: medical condition and test result</caption>
<colgroup>
<col style="width: 58%">
<col style="width: 22%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Condition</th>
<th>Probability</th>
<th>Variable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Having the medical condition</td>
<td>1%</td>
<td>P(A)</td>
</tr>
<tr class="even">
<td>Test positive</td>
<td>unknown</td>
<td>P(B)</td>
</tr>
<tr class="odd">
<td>Given test is positive, has the medical condition</td>
<td>95%</td>
<td>P(B | A)</td>
</tr>
<tr class="even">
<td>Given test is positive, doesn’t have the medical condition</td>
<td>2%</td>
<td>P(B | not A)</td>
</tr>
<tr class="odd">
<td>Does not have the medical condition</td>
<td>99%</td>
<td>1-P(A)</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>Now we are trying to find the probability of the person actually having the medical condition, given the test is positive.</p>
<p>This would be P(A | B).</p>
<p>We cannot use the basic Bayes’ theorem as the P(B) is unknown. This is when we need the expaned version.</p>
<p>Putting all available variables into the formula will look like this: <span class="math display">\[
P(A \mid B) = \frac{0.95 \times 0.01}{(0.95 \times 0.01) + (0.02 \times 0.99)}
\]</span></p>
<div id="024c1896" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>P_A_B <span class="op">=</span> <span class="fl">0.95</span> <span class="op">*</span> <span class="fl">0.01</span> <span class="op">/</span> (<span class="fl">0.95</span><span class="op">*</span><span class="fl">0.01</span> <span class="op">+</span> <span class="fl">0.02</span> <span class="op">*</span> <span class="fl">0.99</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(P_A_B)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.3242320819112628</code></pre>
</div>
</div>
<p><span class="math display">\[P(A \mid B) = 32.4%\]</span></p>
</section>
<section id="case-study---calculate-churn-rate-for-a-customer-type-with-bayes-theorem-or-something-simplier" class="level2">
<h2 class="anchored" data-anchor-id="case-study---calculate-churn-rate-for-a-customer-type-with-bayes-theorem-or-something-simplier">Case study - calculate churn rate for a customer type with Bayes’ theorem (or something simplier)</h2>
<p>Suppose you want to calculate the churn rate of a specific type of customer, e.g.&nbsp;UK customer.</p>
<p>Given you know the number of customer that are in UK, and the number of churned customer in UK, you can easily calculate their churn rate.</p>
<p>Below is a simple data set:</p>
<table class="caption-top table">
<caption>Sample data: total number of customer and churned customer</caption>
<thead>
<tr class="header">
<th>Type</th>
<th>Number of customer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total number of customer</td>
<td>100</td>
</tr>
<tr class="even">
<td>Number of churned customer</td>
<td>60</td>
</tr>
<tr class="odd">
<td>Number of UK customer</td>
<td>50</td>
</tr>
<tr class="even">
<td>Number of churned UK customer</td>
<td>30</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{Churn rate of UK customer} = \frac{\text{Number of churned UK customer}} {\text{Number of UK customer}}\]</span></p>
<p><span class="math display">\[\text{Churn rate of UK customer}  = \frac{30} {50}\]</span></p>
<div id="4331bbc1" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>churn_rate <span class="op">=</span> <span class="dv">30</span><span class="op">/</span><span class="dv">50</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Churn rate of UK customer: </span><span class="sc">{</span>churn_rate<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Churn rate of UK customer: 0.6</code></pre>
</div>
</div>
<p>Now look at the Bayes’ theorem <span class="math display">\[P(A \mid B) = \frac{ P(B \mid A) * P(A) }{ P(B) }\]</span></p>
<p>Put the numbers into the equation <span class="math display">\[ \text{Event A} = \text{Churn rate by all customer}\]</span> <span class="math display">\[ \text{Event B} = \text{Percentage of UK customer}\]</span></p>
<p><span class="math display">\[
P(A \mid B) = \frac{\frac{30}{60} \times \frac{60}{100}}{\frac{50}{100}}
\]</span></p>
<p><span class="math display">\[P(A \mid B) = \frac{30}{60} * \frac{60}{100} * \frac{100}{50}\]</span> <span class="math display">\[P(A \mid B) = \frac{30}{50}\]</span></p>
<div id="f1d2e8e5" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'P(B|A) = </span><span class="sc">{</span><span class="dv">30</span><span class="op">/</span><span class="dv">50</span><span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>P(B|A) = 0.6</code></pre>
</div>
</div>
<p>They both return the same result.</p>
<p>When we know enough variables, it is sufficient for us to directly calculate the churn rate. However when we don’t have enough data, or when the scenario is new, we may need to apply the Bayes’ theorem to get the value we need.</p>
</section>
</section>
<section id="discrete-probability-distribution" class="level1">
<h1>Discrete Probability Distribution</h1>
<section id="binomial-distribtuion" class="level2">
<h2 class="anchored" data-anchor-id="binomial-distribtuion">Binomial distribtuion</h2>
<p>Binomial distribution referes to the calculation of the probability of k out of n ways.</p>
<p>Let’s say we know in a coin toss, there is a 50% chance for it to be a head or a tail. If we toss it for 10 times, what is the probability that we get 5 heads? We can use binomial distribution to calculate the value.</p>
<p>Note that to use binomial distribution, the two results must be mutually exclusive. Like in a coin toss, there can only be a head or toss.</p>
<p>Or in a roll of die, you either get a 3 or not get a 3.</p>
<p>This is how we calculate the binomial distribution:</p>
<p><span class="math display">\[P(x=k) = \frac{n!} {k!(n-k)!} * p^k (1-p)^{n-k}\]</span></p>
<p>The meaning of each variables: <span class="math display">\[k = \text{number of success}\]</span></p>
<p><span class="math display">\[n = \text{number of trials}\]</span></p>
<p><span class="math display">\[p = \text{probability of success on a given trial}\]</span></p>
<p>We can break this down into 2 parts.</p>
<section id="n-choose-k" class="level3">
<h3 class="anchored" data-anchor-id="n-choose-k">n-choose-k</h3>
<p><span class="math display">\[\frac{n!} {k!(n-k)!}\]</span></p>
<p>This is known as n-choose-k, which refers to the number of outcome we want, or the number of success we can get at the given number of trials.</p>
<p>Say you want to know out of 3 coin toss, the number of outcomes where you can get 2 heads.</p>
<p>The formula would be:</p>
<p><span class="math display">\[\text{n-choose-k}=\frac{3!} {2!(3-2)!}\]</span> <span class="math display">\[\text{n-choose-k}=\frac{3*2*1} {2*1*1}\]</span></p>
<div id="d2107985" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>n_choose_k <span class="op">=</span> <span class="dv">3</span><span class="op">*</span><span class="dv">2</span><span class="op">*</span><span class="dv">1</span><span class="op">/</span><span class="dv">2</span><span class="op">*</span><span class="dv">1</span><span class="op">*</span><span class="dv">1</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'n-choose-k = </span><span class="sc">{</span>n_choose_k<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>n-choose-k = 3.0</code></pre>
</div>
</div>
</section>
<section id="probability-of-each-outcome" class="level3">
<h3 class="anchored" data-anchor-id="probability-of-each-outcome">Probability of each outcome</h3>
<p>Now that we know what is the number of outcomes we can get 2 heads, we need to know the probability of each outcome as well, which will allow us to calculate the probability of x=k.</p>
<p><span class="math display">\[p^k(1-p)^{n-k}\]</span></p>
<p>Now we know the chances of getting a head in each toss is 50%</p>
<p>Put it into work, it would be: <span class="math display">\[0.5^2(1-0.5)^{3-2}\]</span></p>
<p><span class="math display">\[=0.5*0.5*0.5\]</span></p>
<div id="8eae6921" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>prob_of_each_outcome <span class="op">=</span> <span class="fl">0.5</span><span class="op">*</span> <span class="fl">0.5</span> <span class="op">*</span> (<span class="dv">1</span><span class="op">-</span><span class="fl">0.5</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Probability of each outcome = </span><span class="sc">{</span>prob_of_each_outcome<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probability of each outcome = 0.125</code></pre>
</div>
</div>
<p>In cases like a coin toss, where you know the chance is 50%, there is also an easier way to get the probability of each outcome.</p>
<p>Say for each coin toss, you can get 2 possible outcomes. For 2 coin toss, you get 2^2, which is 4 outcome.</p>
<p>Now for 3 coin toss, you will get the total possible outcome of 2^3, which is 8.</p>
<p>The probability of getting each outcome is 1/8, which is also 0.125.</p>
<div id="ec721dc5" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'total number of possible outcome = </span><span class="sc">{</span><span class="dv">2</span><span class="op">**</span><span class="dv">3</span><span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'proabbility of each outcome = </span><span class="sc">{</span><span class="dv">1</span><span class="op">/</span><span class="dv">2</span><span class="op">**</span><span class="dv">3</span><span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>total number of possible outcome = 8
proabbility of each outcome = 0.125</code></pre>
</div>
</div>
</section>
<section id="final-outcome" class="level3">
<h3 class="anchored" data-anchor-id="final-outcome">Final outcome</h3>
<p>Now that we can put the two together.</p>
<p><span class="math display">\[p(x=k) = n-choose-k * \text{probability of each outcome}\]</span> <span class="math display">\[p(x=k) = 3*0.125\]</span></p>
<div id="7689a3f0" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>binomial_dist <span class="op">=</span> <span class="dv">3</span><span class="op">*</span><span class="fl">0.125</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'p(x=k) = </span><span class="sc">{</span>binomial_dist<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>p(x=k) = 0.375</code></pre>
</div>
</div>
</section>
<section id="wipcase-study-chances-of-customer-make-a-return-to-a-store" class="level3">
<h3 class="anchored" data-anchor-id="wipcase-study-chances-of-customer-make-a-return-to-a-store">(WIP)Case study: chances of customer make a return to a store</h3>
<p>You are working for a retail store. You know that 10% of all customers visiting the store would make a return.</p>
<p>Now 3 customers visit the store, what is the probability that they will return?</p>
<p>Let’s apply the Binomial distribution formula to all possible situations.</p>
<p>Result should be like below:</p>
<table class="caption-top table">
<caption>Value of p(x=k) for different number of success</caption>
<thead>
<tr class="header">
<th>Number of success</th>
<th>P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>p(x=0)</td>
<td>0.729</td>
</tr>
<tr class="even">
<td>p(x=1)</td>
<td>0.243</td>
</tr>
<tr class="odd">
<td>p(x=2)</td>
<td>0.027</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="poisson-distribution" class="level2">
<h2 class="anchored" data-anchor-id="poisson-distribution">Poisson distribution</h2>
<p>Possion distribution models the probability that a certain number of events will occur during a specific time period.</p>
<p>Below are some practical use cases</p>
<ul>
<li>Calls per hour for a customer service call centre</li>
<li>Visitors per hour for a website</li>
<li>Customers per day at a restaurant</li>
</ul>
<p>Below are necessary for a Poisson experiment</p>
<ul>
<li>The number of events in the experiment can be counted</li>
<li>The mean number of events that occur during a specific time period is known</li>
<li>Each event is independent</li>
</ul>
<section id="poisson-distribution-formula" class="level3">
<h3 class="anchored" data-anchor-id="poisson-distribution-formula">Poisson distribution formula</h3>
<p><span class="math display">\[p(x=k) = \frac{λ^k e^{-λ}}{k!}\]</span></p>
<ul>
<li>λ (lambda) is the mean number of events that occur during a specific time period</li>
<li>k refers to the number of events</li>
<li>e: a constant equal to approximately 2.71828</li>
<li>e^-λ: 1/e^λ</li>
</ul>
</section>
<section id="example-possible-number-of-order-in-a-drive-through-restaurant-wip" class="level3">
<h3 class="anchored" data-anchor-id="example-possible-number-of-order-in-a-drive-through-restaurant-wip">Example: possible number of order in a drive through restaurant (WIP)</h3>
<p>Let’s say we know that the average number of order per minute is 2.</p>
<p>We can use the Poisson formula to determine the probability of the restaurant receiving 0, 1, 2 or 3 orders per minute.</p>
<table class="caption-top table">
<caption>probability of the restaurant receiving number of orders</caption>
<thead>
<tr class="header">
<th>Number of orders</th>
<th>P</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>p(x=0)</td>
<td>0.1353</td>
</tr>
<tr class="even">
<td>p(x=1)</td>
<td>0.2707</td>
</tr>
<tr class="odd">
<td>p(x=2)</td>
<td>0.2707</td>
</tr>
<tr class="even">
<td>p(x=3)</td>
<td>0.1805</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="possion-vs-binomial" class="level2">
<h2 class="anchored" data-anchor-id="possion-vs-binomial">Possion VS Binomial</h2>
<table class="caption-top table">
<caption>Possion VS Binomial</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 42%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Given</th>
<th>Want to Find</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Poisson</td>
<td>The average probability of an event happening for a specific time period</td>
<td>The probability of a certain number of events happening in that time period</td>
</tr>
<tr class="even">
<td>Binomial</td>
<td>An exact probability of an event happening</td>
<td>The probability of the event happening a certain number of times in a repeated trial</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="continuous-probability" class="level1">
<h1>Continuous Probability</h1>
<section id="the-normal-distribution" class="level2">
<h2 class="anchored" data-anchor-id="the-normal-distribution">The normal distribution</h2>
<p>This is also know as the bell curve. It has the following features:</p>
<ul>
<li>The shape is a bell curve</li>
<li>The mean is located at the centre of the curve</li>
<li>The curve is symmetrical on both sides of the center</li>
<li>The total area under the curve equals 1</li>
</ul>
<p>The bell curve follows the emprical rule</p>
<ul>
<li>68% of values fall within 1 standard deviation of the mean</li>
<li>95% of values fall within 2 standard deviation of the mean</li>
<li>99.7% of values fall within 3 standard deviation of the mean</li>
</ul>
</section>
<section id="z-score" class="level2">
<h2 class="anchored" data-anchor-id="z-score">Z-score</h2>
<p>Z-score allows us to compare the normal distribution of different dataset by standardise the normal distribution. It looks at the normal distribution in terms of standard deviation. This is also known as standarised normal distribution</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/z-score_1.png" class="img-fluid figure-img"></p>
<figcaption>Standarised normal distribution</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/z-score_2.png" class="img-fluid figure-img"></p>
<figcaption>Z-score allows us to compare the normla distribution in different datasets</figcaption>
</figure>
</div>
<section id="formula---mean" class="level3">
<h3 class="anchored" data-anchor-id="formula---mean">Formula - mean</h3>
<p>This is how we calculate the Z-score: <span class="math display">\[Z = \frac{x-μ}{σ}\]</span> <span class="math display">\[x = \text{a single data value/raw score}\]</span> <span class="math display">\[μ/mu = \text{the population mean}\]</span> <span class="math display">\[σ/sigma = \text{the poplation standard deviation}\]</span></p>
<p>Now let’s say you have a test score of 133. The test has a mean score of 100 and a standard deviation of 15. The equation would look like this: <span class="math display">\[Z = \frac{133-100}{15}\]</span></p>
<div id="eab6f2c1" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>z_score <span class="op">=</span> (<span class="dv">133</span><span class="op">-</span><span class="dv">100</span>)<span class="op">/</span><span class="dv">15</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Z-score: </span><span class="sc">{</span>z_score<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z-score: 2.2</code></pre>
</div>
</div>
</section>
<section id="formula---proportion" class="level3">
<h3 class="anchored" data-anchor-id="formula---proportion">Formula - proportion</h3>
<p><span class="math display">\[Z = \frac{\hat{P}-P}{\sqrt{\frac{\hat{P}(1-\hat{P})}{n}}}\]</span></p>
<p><span class="math display">\[\hat{P} = \text{Obverved sample proportion}\]</span> <span class="math display">\[P = \text{Population proportion}\]</span> <span class="math display">\[n = \text{Sample size}\]</span></p>
<p>This measures the standard error of the proportion. Note that if we are calculating the Z-score for a hypothesis test, you may replace the sample proportion (p hat) with the population proportion (p). In hypothesis testing, we are testing whether the true population proportion P is equal to the hypothesized value. Therefore, we calculate the standard error assuming the null hypothesis is true and use P to determine how much variability we expect in the sample proportions. <span class="math display">\[\sqrt{\frac{\hat{P}(1-\hat{P})}{n}} = \text{Sample error of the proportion}\]</span></p>
</section>
<section id="python" class="level3">
<h3 class="anchored" data-anchor-id="python">Python</h3>
<p>You can use the z-score function in the scipy package to calculate the z-score of each datapoint in your dataframe.</p>
</section>
</section>
<section id="smaller-sample-size---t-score-and-t-distribution" class="level2">
<h2 class="anchored" data-anchor-id="smaller-sample-size---t-score-and-t-distribution">Smaller sample size - T-score and T-distribution</h2>
<p>The Student’s t-distribution, often just called the t-distribution, is a probability distribution that is used when estimating the mean of a normally distributed population in situations where the sample size is small, and the population standard deviation is unknown. This distribution was developed by William Sealy Gosset under the pseudonym “Student.”</p>
<p>It is similar to the normal distribution but more compressed with heavier tails.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/t-distrbution.png" class="img-fluid figure-img"></p>
<figcaption>Z-distrbution vs T-distribution</figcaption>
</figure>
</div>
<p>Below are the differences between T-score and Z-score:</p>
<table class="caption-top table">
<caption>T-score VS Z-score</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 40%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Z-Score</th>
<th>T-Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample Size</td>
<td>Large samples (n&gt;30n&gt;30)</td>
<td>Small samples (n≤30n≤30)</td>
</tr>
<tr class="even">
<td>Population Standard Deviation</td>
<td>Known</td>
<td>Unknown</td>
</tr>
<tr class="odd">
<td>Distribution</td>
<td>Normal distribution</td>
<td>T-distribution (heavier tails)</td>
</tr>
<tr class="even">
<td>Applications</td>
<td>Standardized tests, quality control, large-scale surveys</td>
<td>Small-sample studies, medical trials, social science experiments</td>
</tr>
<tr class="odd">
<td>Type of Data</td>
<td>Population data or large samples</td>
<td>Sample data when population parameters are unknown</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="sampling-distribution" class="level1">
<h1>Sampling distribution</h1>
<section id="standard-error-of-the-mean" class="level2">
<h2 class="anchored" data-anchor-id="standard-error-of-the-mean">Standard Error of the Mean</h2>
<p>The standard error formula is base on the math assumption of repeated sampling, and it calculates the possible range of the actual mean based on one sample.</p>
<p><span class="math display">\[\text{Standard error of the mean} = \frac{σ*}{\sqrt{n}}\]</span> <span class="math display">\[σ = \text{Standard deviation of the population}\]</span></p>
<p>*The standard deviation of the population is usually unknown, so in practice we often use the standard deviation o the sample instead.</p>
<p><span class="math display">\[\text{Standard error of the mean} = \frac{s}{\sqrt{n}}\]</span> <span class="math display">\[s = \text{The sample standard deviation}\]</span> <span class="math display">\[n = \text{The sample size}\]</span></p>
<p>The larger the sample size is,the smaller the error would be.</p>
<p>Now let’s say we have a sample of 100 penguine, which has a mean weight of 3 pounds and a standard deviation of 1 pound.</p>
<p><span class="math display">\[\text{Stand error of the mean} = \frac{1}{\sqrt{100}}\]</span></p>
<div id="ba70fd51" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sample_std <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>n_sqr <span class="op">=</span> math.sqrt(<span class="dv">100</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>standard_error <span class="op">=</span> sample_std<span class="op">/</span>n_sqr</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(standard_error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.1</code></pre>
</div>
</div>
<p>Now while the best estimated mean of the population will still be 3 pounds, you know that the mean will vary with a standard deviation of 0.1 pound.</p>
</section>
<section id="the-central-limit-theorem" class="level2">
<h2 class="anchored" data-anchor-id="the-central-limit-theorem">The Central Limit Theorem</h2>
<p>The sample distribution of the mean approaches a normal distribution when the sample size increases.</p>
</section>
<section id="standard-error-of-the-proportion" class="level2">
<h2 class="anchored" data-anchor-id="standard-error-of-the-proportion">Standard Error of the Proportion</h2>
<section id="theory-and-formula" class="level3">
<h3 class="anchored" data-anchor-id="theory-and-formula">Theory and formula</h3>
<p>The standard error of proportion measures the standard error of a sampling proportion.</p>
<p><span class="math display">\[SE(\hat{p}) = \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
<p><span class="math display">\[\hat{p} (\text{p hat}) = \text{population proportion}\]</span></p>
<p><span class="math display">\[n = \text{sample size}\]</span></p>
<p>Say you are researching a population of 100,000, in a sample with 100 people, 10% of them prefer slipon sneaker.</p>
<p><span class="math display">\[SE(\hat{p}) = \sqrt{\frac{0.1(1-0.1)}{100}}\]</span></p>
<div id="a93b7cb6" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>phat <span class="op">=</span> <span class="fl">0.1</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>sample <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>sample_error <span class="op">=</span> math.sqrt(<span class="fl">0.1</span><span class="op">*</span>(<span class="dv">1</span><span class="op">-</span><span class="fl">0.1</span>)<span class="op">/</span><span class="dv">100</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sample_error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.030000000000000002</code></pre>
</div>
</div>
<p>The sample error is 0.03, which means that the estimate population proportion who prefer slipon sneaker is 10%, which would deviate for +/-3%.</p>
</section>
<section id="case-study-apply-the-standard-error-of-the-proportion-to-churn-rate" class="level3">
<h3 class="anchored" data-anchor-id="case-study-apply-the-standard-error-of-the-proportion-to-churn-rate">Case study: apply the standard error of the proportion to churn rate</h3>
<p>Say you know that you have 100 customers (current and churned) in Scotland, and their churn rate is 60%. You can use the standard error formula to understand how much the sample proportion (in your case, the sample churn rate) is expected to vary from the true population proportion (the true churn rate for all current and future customers).</p>
<div id="59928e49" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Given data</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>p_hat <span class="op">=</span> <span class="fl">0.60</span>  <span class="co"># Sample churn rate</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">100</span>       <span class="co"># Sample size</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard error calculation</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>standard_error <span class="op">=</span> math.sqrt((p_hat <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> p_hat)) <span class="op">/</span> n)</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(standard_error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.04898979485566356</code></pre>
</div>
</div>
<p>The standard error is around 0.05, which means that the standard deviation of the churn rate for current and future Scotland customer will be at 60%, vary for +-5%.</p>
<p>You can further calculate the confidence level base on the standard error and sample size, to understand how reliable this is.</p>
</section>
</section>
</section>
<section id="confidence-level" class="level1">
<h1>Confidence level</h1>
<p>Imagine you want to estimate the mean weight of a population of 10,000 penguins. Instead of weighing every single penguin, you select a sample of 100 penguins. The mean weight of your sample is 30 pounds. Based on your sample data, you construct a 95% confidence interval between 28 pounds and 32 pounds.</p>
<p>95 CI [28, 32]</p>
<p>Usual confidence level choosen are as follow:</p>
<ul>
<li>90%</li>
<li>95%</li>
<li>99%</li>
</ul>
<section id="interpret-the-confidence-interval" class="level2">
<h2 class="anchored" data-anchor-id="interpret-the-confidence-interval">Interpret the confidence interval</h2>
<p>Technically, 95% confidence means that if you take repeated random samples from a population, and construct a confidence interval for each sample using the same method, you can expect that 95% of these intervals will capture the population mean. You can also expect that 5% of the total will not capture the population mean.</p>
<p>The confidence level refers to the long-term success rate of the method, or the estimation process based on random sampling.</p>
<p>Imagine you take 20 random samples of 100 penguins each from the penguin population, and calculate a 95% confidence interval for each sample. You can expect that approximately 19 of the 20 intervals, or 95% of the total, will contain the actual population mean weight of 31 pounds. One such interval will be the range of values between 28 pounds and 32 pounds.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/confidence_intervals.png" class="img-fluid figure-img"></p>
<figcaption>Interpret the confidence interval</figcaption>
</figure>
</div>
</section>
<section id="incorrect-interpretations" class="level2">
<h2 class="anchored" data-anchor-id="incorrect-interpretations">Incorrect interpretations</h2>
<ul>
<li>There is a 95% probability that the population mean falls within the constructed interval. (It’s not true!)</li>
</ul>
<p>What you can say is that if you take repeated random samples from the population, and construct a confidence interval for each sample using the same method, you can expect 95% of your intervals to capture the population mean.</p>
<p>Pro tip: Remember that a 95% confidence level refers to the success rate of the estimation process.</p>
<ul>
<li>95% of all of the data values in the population fall within the interval (Also not true. )</li>
</ul>
</section>
<section id="construct-confidence-interval-for-porportion" class="level2">
<h2 class="anchored" data-anchor-id="construct-confidence-interval-for-porportion">Construct confidence interval for porportion</h2>
<ol type="1">
<li>Identify a sample statistic</li>
<li>Choose a confidence level</li>
<li>Find the margin of error</li>
<li>Calculate the interval</li>
</ol>
<p>Let’s say you work for election polling. Below would be the associate data point.</p>
<table class="caption-top table">
<caption>Construct confidence interval for election polling</caption>
<colgroup>
<col style="width: 42%">
<col style="width: 42%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Metric</th>
<th>Data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample statistic</td>
<td>Percentage of sample that prefer candidate A</td>
<td>55%</td>
</tr>
<tr class="even">
<td>Confidence level</td>
<td>95%</td>
<td>1.96</td>
</tr>
<tr class="odd">
<td>Standard error</td>
<td>Standard error of poportion from the sample (assume sample size is 100)</td>
<td>5%</td>
</tr>
<tr class="even">
<td>Margin of error</td>
<td>Assume a large sample size and normal distribution, it would be z-score * standard error</td>
<td>1.96*0.05=0.098</td>
</tr>
<tr class="odd">
<td>Upper limit of the interval</td>
<td>Sample stat + margin of error</td>
<td>55%+9.8%=64.8%</td>
</tr>
<tr class="even">
<td>Lower limit of the interval</td>
<td>Sample stat - margin of error</td>
<td>55%-9.8%=45.2%</td>
</tr>
<tr class="odd">
<td>Confidence Interval</td>
<td>Upper limit - lower limit</td>
<td>64.8%-45.2%=19.6%</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<caption>Common confidence level and associated z-score</caption>
<thead>
<tr class="header">
<th>Confidence Level</th>
<th>Z-score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90%</td>
<td>1.645</td>
</tr>
<tr class="even">
<td>95%</td>
<td>1.96</td>
</tr>
<tr class="odd">
<td>99%</td>
<td>2.58</td>
</tr>
</tbody>
</table>
<p>The formula for calculate margin of error in a large sample size would be:</p>
<p><span class="math display">\[\text{Margin of error} = \text{z-score}*\text{standard error}\]</span></p>
<p>Note that in a smaller sample size, we will need to use <strong>t-score</strong> to calculate the margin of error.</p>
<p>In the situation of polling, we will use the standard error of poportion for the standard error calculation:</p>
<p><span class="math display">\[SE(\hat{p}) = \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}\]</span></p>
<p><span class="math display">\[\text{Sample proportion}=0.55\]</span> <span class="math display">\[\text{Sample size}=100\]</span></p>
<div id="1298bb86" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>p<span class="op">=</span><span class="fl">0.55</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>n<span class="op">=</span><span class="dv">100</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> math.sqrt(p<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p)<span class="op">/</span>n)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Standard error of porportion: </span><span class="sc">{</span>se<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Standard error of porportion: 0.049749371855330994</code></pre>
</div>
</div>
</section>
<section id="construct-confidence-interval-for-mean" class="level2">
<h2 class="anchored" data-anchor-id="construct-confidence-interval-for-mean">Construct confidence interval for mean</h2>
<ol type="1">
<li>Identify a sample statistic</li>
<li>Choose a confidence level</li>
<li>Find the margin of error</li>
<li>Calculate the interval</li>
</ol>
<p>Let’s say this time you work for a a cellphone manufactory company, and you are trying to get the average battery life of a new cellphone battery.</p>
<table class="caption-top table">
<caption>Construct confidence interval for cellphone battery</caption>
<colgroup>
<col style="width: 42%">
<col style="width: 42%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Metric</th>
<th>Data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample statistic</td>
<td>Mean</td>
<td>20.5</td>
</tr>
<tr class="even">
<td>Confidence level</td>
<td>95%</td>
<td>1.96</td>
</tr>
<tr class="odd">
<td>Standard error</td>
<td>Standard error of poportion from the sample (assume sample size is 100)</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>Margin of error</td>
<td>Assume a large sample size and normal distribution, it would be z-score * standard error</td>
<td>1.96*0.15=0.294</td>
</tr>
<tr class="odd">
<td>Upper limit of the interval</td>
<td>Sample stat + margin of error</td>
<td>20.5+0.294=20.794</td>
</tr>
<tr class="even">
<td>Lower limit of the interval</td>
<td>Sample stat - margin of error</td>
<td>20.5-0.294=20.206</td>
</tr>
<tr class="odd">
<td>Confidence Interval</td>
<td>Upper limit - lower limit</td>
<td>20.794-20.206</td>
</tr>
</tbody>
</table>
<p>We want to use the standard error of the mean to calculate the margin of error.</p>
<p>As we know the standard deviation of the population, we can use that for the formula. <span class="math display">\[\text{Standard error of the mean} = \frac{σ}{\sqrt{n}}\]</span></p>
<div id="8f390015" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>sigma<span class="op">=</span><span class="fl">1.5</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>n<span class="op">=</span><span class="dv">100</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>se <span class="op">=</span> <span class="fl">1.5</span><span class="op">/</span>math.sqrt(<span class="dv">100</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Standard error: </span><span class="sc">{</span>se<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Standard error: 0.15</code></pre>
</div>
</div>
</section>
<section id="calculate-confidence-interval-with-scipy" class="level2">
<h2 class="anchored" data-anchor-id="calculate-confidence-interval-with-scipy">Calculate confidence interval with SciPy</h2>
<p>First let’s generate a random sample of a survey result of government support rate by town.</p>
<div id="95d62ad8" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of rows</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>n_rows <span class="op">=</span> <span class="dv">500</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate town names (using 'Town' with an index for uniqueness)</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>towns <span class="op">=</span> [<span class="ss">f'Town_</span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss">'</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_rows)]</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate random support rates (between 0 and 100)</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>support_rates <span class="op">=</span> np.random.uniform(<span class="dv">0</span>, <span class="dv">1</span>, n_rows).<span class="bu">round</span>(<span class="dv">2</span>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the DataFrame</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>data <span class="op">=</span> pd.DataFrame({</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">'town'</span>: towns,</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">'support_rate'</span>: support_rates</span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>data.head()  <span class="co"># Display the first few rows of the dataset</span></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>data.describe()</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>data[<span class="st">'support_rate'</span>].mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>0.49871999999999994</code></pre>
</div>
</div>
<p>The average support rate by town for the whole data set is 0.4987.</p>
<p>Now take a random sample size of 50.</p>
<div id="df2c6d47" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>data_sample <span class="op">=</span> data.sample(n<span class="op">=</span><span class="dv">50</span>, replace<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">30624300</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To get the confidence interval of the sample, we will need to know the below:</p>
<ul>
<li>Confidence level</li>
<li>Sample mean</li>
<li>Sample standard error</li>
</ul>
<p>Assume we want the confidence level of 95 or 99.</p>
<div id="760ae06e" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>confi_level <span class="op">=</span> <span class="fl">0.95</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="op">=</span> data_sample[<span class="st">'support_rate'</span>].mean()</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Sample mean: </span><span class="sc">{</span>sample_mean<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>standard_error <span class="op">=</span> data_sample[<span class="st">'support_rate'</span>].std()<span class="op">/</span>np.sqrt(data_sample.shape[<span class="dv">0</span>])</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Standard error: </span><span class="sc">{</span>standard_error<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>conf_interval <span class="op">=</span> stats.norm.interval(confi_level, loc<span class="op">=</span>sample_mean, scale<span class="op">=</span>standard_error)</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Confidence interval of the sample with confidence level of </span><span class="sc">{</span>confi_level<span class="sc">}</span><span class="ss">: '</span>)</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(conf_interval)</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>confi_level <span class="op">=</span> <span class="fl">0.99</span></span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Confidence interval of the sample with confidence level of </span><span class="sc">{</span>confi_level<span class="sc">}</span><span class="ss">: '</span>)</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(conf_interval)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample mean: 0.5239999999999999

Standard error: 0.047072675032271936

Confidence interval of the sample with confidence level of 0.95: 
(0.4317392522807891, 0.6162607477192107)

Confidence interval of the sample with confidence level of 0.99: 
(0.4317392522807891, 0.6162607477192107)</code></pre>
</div>
</div>
</section>
</section>
<section id="hypotheses-testing" class="level1">
<h1>Hypotheses testing</h1>
<section id="steps-for-conducting-a-hypothesis-test" class="level2">
<h2 class="anchored" data-anchor-id="steps-for-conducting-a-hypothesis-test">Steps for conducting a hypothesis test</h2>
<ol type="1">
<li><p>State the null hypothesis and the alternative hypothesis.</p></li>
<li><p>Choose a significant level.</p></li>
<li><p>Find the p-value.</p></li>
<li><p>Reject or fail to reject the null hypothesis. (by comparing p-value and significant level)</p></li>
</ol>
</section>
<section id="null-vs-alternative-hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="null-vs-alternative-hypothesis">Null VS Alternative hypothesis</h2>
<table class="caption-top table">
<caption>Null VS Alternative hypothesis</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 41%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Null hypothesis (H0)</strong></th>
<th><strong>Alternative hypothesis (Ha)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Claims</strong></td>
<td>There is no effect in the population.</td>
<td>There is an effect in the population.</td>
</tr>
<tr class="even">
<td><strong>Assumption</strong></td>
<td>Assumed to be true unless there is convincing evidence to the contrary.</td>
<td>Accepted as true only if there is convincing evidence for it.</td>
</tr>
<tr class="odd">
<td><strong>Language</strong></td>
<td><ul>
<li>No Effect</li>
<li>No difference</li>
<li>No relationship</li>
<li>No change</li>
</ul></td>
<td><ul>
<li>An effect</li>
<li>A difference</li>
<li>A relationship</li>
<li>A change</li>
</ul></td>
</tr>
<tr class="even">
<td><strong>Symbols</strong></td>
<td>Equality (=, ≤, ≥)</td>
<td>Inequality (≠, &lt;, &gt;)</td>
</tr>
</tbody>
</table>
</section>
<section id="significant-level" class="level2">
<h2 class="anchored" data-anchor-id="significant-level">Significant level</h2>
<p>This is the threshold at which we will consider our result statiscally significant. It is also the probability of rejecting the null hypothesis when it is true.</p>
<p>5% is the most common standard for significant level.</p>
<p>For more strict result, 1% is used.</p>
</section>
<section id="p-value" class="level2">
<h2 class="anchored" data-anchor-id="p-value">P-value</h2>
<p>The probability of observing a difference in your result as or more extreme than the difference observed when the null hypothesis is true.</p>
<p>It is used to compared against the significant level.</p>
<p>The p-value is calculated by test statistic, a value that shows how closely your observed data matches the distribution expected under the null hypothesis. After getting a t-score or a z-score from a t-test or z-test, you can calculate the p-value by</p>
</section>
<section id="examples-of-null-and-alternative-hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="examples-of-null-and-alternative-hypothesis">Examples of Null and Alternative hypothesis</h2>
<section id="example1-mean-weight" class="level3">
<h3 class="anchored" data-anchor-id="example1-mean-weight">Example#1: Mean weight</h3>
<p>An organic food company is famous for their granola. The company claims each bag they produce contains 300 grams of granola—no more and no less. To test this claim, a quality control expert measures the weight of a random sample of 40 bags.</p>
<ul>
<li>H0: μ = 300 (the mean weight of all produced granola bags is equal to 300 grams)</li>
<li>Ha: μ ≠ 300 (the mean weight of all produced granola bags is not equal to 300 grams)</li>
</ul>
</section>
<section id="example2-mean-height" class="level3">
<h3 class="anchored" data-anchor-id="example2-mean-height">Example#2: Mean height</h3>
<p>Suppose it’s assumed that the mean height of a certain species of tree is 30 feet tall. However, one ecologist claims the actual mean height is greater than 30 feet. To test this claim, the ecologist measures the height of a random sample of 50 trees.</p>
<ul>
<li>H0: μ ≤ 30 (the mean height of this species of tree is equal to or less than 30 feet)</li>
<li>Ha: μ &gt; 30 (the mean height of this species of tree is greater than 30 feet)</li>
</ul>
</section>
<section id="example3-proportion-of-employees" class="level3">
<h3 class="anchored" data-anchor-id="example3-proportion-of-employees">Example#3: Proportion of employees</h3>
<p>A corporation claims that at least 80% of all employees are satisfied with their job. However, an independent researcher believes that less than 80% of all employees are satisfied with their job. To test this claim, the researcher surveys a random sample of 100 employees.</p>
<ul>
<li>H0: p ≥ 0.80 (the proportion of all employees who are satisfied with their job is equal to or greater than 80%)</li>
<li>Ha: p &lt; 0.80 (the proportion of all employees who are satisfied with their job is less than 80%)</li>
</ul>
</section>
</section>
<section id="type-i-and-type-ii-errors" class="level2">
<h2 class="anchored" data-anchor-id="type-i-and-type-ii-errors">Type I and Type II errors</h2>
<p>When you decide to reject or fail to reject the null hypothesis, there are four possible outcomes–two represent correct choices, and two represent errors. You can:</p>
<ul>
<li>Reject the null hypothesis when it’s actually true (Type I error)</li>
<li>Reject the null hypothesis when it’s actually false (Correct)</li>
<li>Fail to reject the null hypothesis when it’s actually true (Correct)</li>
<li>Fail to reject the null hypothesis when it’s actually false (Type II error)</li>
</ul>
</section>
<section id="one-sample-tests---t-test-vs-z-test" class="level2">
<h2 class="anchored" data-anchor-id="one-sample-tests---t-test-vs-z-test">One sample tests - T-test vs z-test</h2>
<p>One-sample tests are usually used to determine whether a population mean is equal to a specific value.</p>
<p>The primary difference between the one-tail t-test and the one-tail z-test lies in the distribution they use, which depends on whether the population standard deviation is known and the sample size. Both tests are used to determine if there is a significant difference between the sample mean and the population mean, but they differ slightly in their formula.</p>
<section id="one-tail-t-test" class="level3">
<h3 class="anchored" data-anchor-id="one-tail-t-test">One tail t-test</h3>
<p>The t-test is typically used when:</p>
<ul>
<li>The sample size is small (generally n&lt;30).</li>
<li>The population standard deviation σ is unknown, so we estimate it using the sample standard deviation s.</li>
</ul>
<p>The formula for the t-test statistic is: <span class="math display">\[t = \frac{\bar{x}-μ}{\frac{s}{\sqrt{n}}}\]</span></p>
<p>Where:</p>
<ul>
<li>x̄ = sample mean</li>
<li>μ = population mean (hypothesized)</li>
<li>s = sample standard deviation</li>
<li>n = sample size</li>
<li>s/sqrt(n) = standard error of the sample mean</li>
</ul>
<p>The result is compared with a t-distribution with n−1 degrees of freedom to get the critical value for a one-tail test.</p>
</section>
<section id="one-tail-z-test" class="level3">
<h3 class="anchored" data-anchor-id="one-tail-z-test">One tail z-test</h3>
<p>The z-test is typically used when:</p>
<ul>
<li><p>The sample size is small (generally n&lt;30).</p></li>
<li><p>The population standard deviation σ is unknown, so we estimate it using the sample standard deviation s.</p></li>
<li><p>The sample size is large (typically n≥30).</p></li>
<li><p>The population standard deviation σ is known.</p></li>
</ul>
<p>The formula for the z-test statistic is: <span class="math display">\[z = \frac{\bar{x}-μ}{\frac{σ}{\sqrt{n}}}\]</span></p>
<p>Where:</p>
<ul>
<li>x̄ = sample mean</li>
<li>μ = population mean (hypothesized)</li>
<li>σ = population standard deviation</li>
<li>n = sample size</li>
<li>σ/sqrt(n) = standard error of the population mean</li>
</ul>
<p>The result is compared with the standard normal distribution (Z-distribution) to get the critical value for a one-tail test.</p>
</section>
</section>
<section id="calculate-the-p-value-from-a-one-tailtwo-tail-z-score-and-t-score" class="level2">
<h2 class="anchored" data-anchor-id="calculate-the-p-value-from-a-one-tailtwo-tail-z-score-and-t-score">Calculate the p-value from a one-tail/two-tail z-score and t-score</h2>
<section id="z-score-1" class="level3">
<h3 class="anchored" data-anchor-id="z-score-1">Z-score</h3>
<p><strong>Two-tail z-test</strong> <span class="math display">\[\text{p-value} = 2 \times P(Z \geq |z|)\]</span></p>
<p><strong>Right-tail z-test</strong> <span class="math display">\[\text{p-value} = P(Z \geq z)\]</span></p>
<p><strong>Left-tail z-test</strong> <span class="math display">\[\text{p-value} = P(Z \leq z)\]</span></p>
<p><strong>Example</strong> Suppose z = 1.96 in a two-tail test.</p>
<p><span class="math display">\[P(Z \geq 1.96) = 0.025\]</span> <span class="math display">\[\text{p-value} = 2*0.025 = 0.05\]</span></p>
<div id="b80c9615" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>((<span class="dv">1</span><span class="op">-</span>norm.cdf(<span class="bu">abs</span>(<span class="fl">1.96</span>)))<span class="op">*</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0.04999579029644097</code></pre>
</div>
</div>
<p><strong>Calulation in python</strong></p>
<div id="e3791cc6" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Given z-score</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> <span class="fl">1.96</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-tailed test p-value</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>p_value_two_tailed <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> norm.cdf(<span class="bu">abs</span>(z)))</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Right-tailed test p-value</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>p_value_right_tailed <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> norm.cdf(z)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Left-tailed test p-value</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>p_value_left_tailed <span class="op">=</span> norm.cdf(z)</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Two-tailed p-value:"</span>, p_value_two_tailed)</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Right-tailed p-value:"</span>, p_value_right_tailed)</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Left-tailed p-value:"</span>, p_value_left_tailed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Two-tailed p-value: 0.04999579029644097
Right-tailed p-value: 0.024997895148220484
Left-tailed p-value: 0.9750021048517795</code></pre>
</div>
</div>
</section>
<section id="t-score" class="level3">
<h3 class="anchored" data-anchor-id="t-score">T-score</h3>
<p>In a t-test, you also want to determine the degree of freedom (df). In a one sample t-test, it would usually be n-1. <span class="math display">\[df = n-1\]</span></p>
<p>Below are some different cases of degree of freedom baseon the test we conduct:</p>
<table class="caption-top table">
<caption>Degree of freedom in different stat tests</caption>
<colgroup>
<col style="width: 41%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Degrees of Freedom (df)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>One-Sample t-Test</td>
<td>n−1</td>
</tr>
<tr class="even">
<td>Paired t-Test</td>
<td>n−1</td>
</tr>
<tr class="odd">
<td>Two-Sample t-Test (Equal Variances)</td>
<td>n1+n2−2</td>
</tr>
<tr class="even">
<td>Two-Sample t-Test (Unequal Variances)</td>
<td>Approximate&nbsp;df&nbsp;based on Welch-Satterthwaite equation</td>
</tr>
<tr class="odd">
<td>ANOVA (Between Groups)</td>
<td>k−1</td>
</tr>
<tr class="even">
<td>ANOVA (Within Groups)</td>
<td>N−k</td>
</tr>
<tr class="odd">
<td>Chi-Square (Goodness-of-Fit)</td>
<td>k−1</td>
</tr>
<tr class="even">
<td>Chi-Square (Independence)</td>
<td>(r−1)(c−1)</td>
</tr>
<tr class="odd">
<td>Linear Regression (Residual)</td>
<td>n−p−1</td>
</tr>
<tr class="even">
<td>F-Test</td>
<td>df1,df2 ​</td>
</tr>
</tbody>
</table>
<p><strong>Two-tail t-test</strong> <span class="math display">\[\text{p-value} = 2 \times P(T \geq |t|;df)\]</span></p>
<p><strong>Right-tail t-test</strong> <span class="math display">\[\text{p-value} = P(T \geq t;df)\]</span></p>
<p><strong>Left-tail t-test</strong> <span class="math display">\[\text{p-value} = P(T \leq t;df)\]</span></p>
<p><strong>Calculation in python</strong></p>
<div id="b5db94a8" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Given t-score and degrees of freedom</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>t_score <span class="op">=</span> <span class="fl">2.0</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> <span class="dv">10</span>  <span class="co"># degrees of freedom</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-tailed test p-value</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>p_value_two_tailed_t <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> t.cdf(<span class="bu">abs</span>(t_score), df))</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Right-tailed test p-value</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>p_value_right_tailed_t <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> t.cdf(t_score, df)</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Left-tailed test p-value</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>p_value_left_tailed_t <span class="op">=</span> t.cdf(t_score, df)</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Two-tailed p-value (t-test):"</span>, p_value_two_tailed_t)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Right-tailed p-value (t-test):"</span>, p_value_right_tailed_t)</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Left-tailed p-value (t-test):"</span>, p_value_left_tailed_t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Two-tailed p-value (t-test): 0.07338803477074052
Right-tailed p-value (t-test): 0.03669401738537026
Left-tailed p-value (t-test): 0.9633059826146297</code></pre>
</div>
</div>
<div class="sourceCode" id="cb41"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="in">stats.ttest_1samp(a = aqi_michigan['aqi'], popmean=10, alternative='greater')</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="one-sample-tests---z-test" class="level2">
<h2 class="anchored" data-anchor-id="one-sample-tests---z-test">One sample tests - Z-test</h2>
<section id="assumption" class="level3">
<h3 class="anchored" data-anchor-id="assumption">Assumption:</h3>
<ul>
<li>The data is a random sample of a normally distributed population</li>
<li>The standard deviation of the population is known</li>
</ul>
</section>
<section id="case-study-online-delivery" class="level3">
<h3 class="anchored" data-anchor-id="case-study-online-delivery">Case Study: Online Delivery</h3>
<p>Let’s say you work for an online delivery company. Currently the average delivery time is 40 minutes, with a standard deviation of 5 minutes.</p>
<p>Recently, the company launched a new training program to make the delivery more efficient. After the drivers completed the training program, the company tracked a random sample of 50 deliveries to understand how long a delivery take. The sample has an average delivery time of 38 minutes, and a standard deviation of 5 minutes.</p>
<p>Now the company wants to know if the decrease in delivery time is due to chance, or is statistically significant.</p>
<p>We can determine this with a one hypothesis z-test.</p>
<p><strong>Population</strong></p>
<ul>
<li>Mean = 40 min</li>
<li>Standard deviation = 5 min</li>
</ul>
<p><strong>Sample</strong></p>
<ul>
<li>Mean = 38 min</li>
<li>Standard deviation = 5 min</li>
</ul>
<p>Let’s build the hypothesis step by step:</p>
<p><strong>Null hypothesis</strong></p>
<p>The average delivery time equals 40 minutes.</p>
<p><strong>Alternative hypothesis</strong></p>
<p>The average delivery time is less than 40 minutes.</p>
<p><strong>Significant level</strong></p>
<p>5%</p>
<p>This is the threshold at which we will consider our result statiscally significant. It is also the probability of rejecting the null hypothesis when it is true.</p>
<p><strong>P-value</strong></p>
<p>The probability of observing a difference in your result as or more extreme than the difference observed when the null hypothesis is true.</p>
<p>The probability of observing a difference that is two minutes or greater if the null hypothesis is true. If the probability of this outcome is very unlikely, in particular, if your p-value is less than your significance level of five percent, then you’ll reject the null hypothesis.</p>
<p>If p-value &lt; 5%, then reject the null hypothesis.</p>
<p>In this case, as we are using z-test, we will calculate the z-score to find the p-value.</p>
<p><span class="math display">\[z = \frac{\bar{x}-μ}{\frac{σ}{\sqrt{n}}}\]</span></p>
<p>Where:</p>
<ul>
<li>x̄ = sample mean</li>
<li>μ = population mean (hypothesized)</li>
<li>σ = population standard deviation</li>
<li>n = sample size</li>
<li>σ/sqrt(n) = standard error of the population mean</li>
</ul>
<p><span class="math display">\[z = \frac{38-40}{\frac{5}{\sqrt{50}}}\]</span></p>
<div id="3ba1ced2" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="op">=</span> <span class="dv">38</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>pop_mean <span class="op">=</span> <span class="dv">40</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>pop_std <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>z_score <span class="op">=</span> (sample_mean<span class="op">-</span>pop_mean)<span class="op">/</span>(pop_std<span class="op">/</span>math.sqrt(sample_size))</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> norm.cdf(z_score)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Z-score: </span><span class="sc">{</span>z_score<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'P-value: </span><span class="sc">{</span>p_value<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z-score: -2.8284271247461903
P-value: 0.0023388674905236283</code></pre>
</div>
</div>
<p>In this case, the z-score is -2.8284. P-value is 0.0023 or 0.23%.</p>
<p>In this case, it is very unlikely that the mean delivery time is 38 minutes when the null hypothesis is true. In other words, it’s highly unlikely that the sample mean of 38 is due to chance. Therefore we reject the null hypothesis.</p>
<p>The p-value we calculated here is the probability for when the z-score &lt;= -2.8284 in a normal distribution, which is the red area in the image below.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/z_test_p_value.png" class="img-fluid figure-img"></p>
<figcaption>P value according to the z-score</figcaption>
</figure>
</div>
</section>
</section>
<section id="two-sample-test" class="level2">
<h2 class="anchored" data-anchor-id="two-sample-test">Two-sample test</h2>
<p>A two-sample test determines whether two population means are equal to each other. It is frequently used in A/B testing.</p>
</section>
<section id="two-sample-t-test-for-means" class="level2">
<h2 class="anchored" data-anchor-id="two-sample-t-test-for-means">Two-sample t-test for means</h2>
<section id="assumption-1" class="level3">
<h3 class="anchored" data-anchor-id="assumption-1">Assumption</h3>
<ul>
<li>The two samples are independent of each other</li>
<li>For each sample, the data is drawn randomly from a normally distributed population</li>
<li>The population standard deviation is unknown</li>
</ul>
</section>
<section id="hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis">Hypothesis</h3>
<ul>
<li>Null: There is no difference in the mean on version A and version B</li>
<li>Alternative: There is a difference in the mean on version A and version B</li>
<li>Significant level: Usually 5%, can also be 1% or 10%</li>
<li>P-value: The probability of observing a difference in your sample means as or more extreme than the difference observed when the null hypothesis is true</li>
</ul>
</section>
<section id="code" class="level3">
<h3 class="anchored" data-anchor-id="code">Code</h3>
<p>If you have the full sample data, you can leverage Scipy’s t-test functions to calculate the t-score and p-value as below:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="in">stats.ttest_ind(a=sampled_state21['OVERALL_LI'], b=sampled_state28['OVERALL_LI'], equal_var=False, alternative='two-sided')</span></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>It should return the t-score and p-value like below: Ttest_indResult(statistic=2.8980444277268735, pvalue=0.006421719142765231)</p>
</section>
<section id="t-score-for-two-sample-t-test" class="level3">
<h3 class="anchored" data-anchor-id="t-score-for-two-sample-t-test">T-score for two-sample t-test</h3>
<p><span class="math display">\[t = \frac{(\bar{x}_1 - \bar{x}_2)}{\sqrt{({\frac{s^2_1}{n_1} + \frac{s^2_2}{n_2}})}}\]</span></p>
<ul>
<li>x̄ = sample mean</li>
<li>s = sample standard deviation</li>
<li>n = sample size</li>
<li>s^2/n = variance of the sample mean</li>
</ul>
</section>
<section id="get-p-value-from-two-sample-t-test" class="level3">
<h3 class="anchored" data-anchor-id="get-p-value-from-two-sample-t-test">Get p-value from two-sample t-test</h3>
<p>In a two-sample t-test, you would want the below:</p>
<div id="b8af73c0" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Given t-score and degrees of freedom</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>t_score <span class="op">=</span> <span class="op">-</span><span class="fl">1.2541</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> <span class="dv">40</span><span class="op">+</span><span class="dv">38</span><span class="op">-</span><span class="dv">2</span>  <span class="co"># degrees of freedom</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-tailed test p-value</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>p_value_two_tailed_t <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> t.cdf(<span class="bu">abs</span>(t_score), df))</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Two-tailed p-value (t-test):"</span>, p_value_two_tailed_t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Two-tailed p-value (t-test): 0.21364931373347917</code></pre>
</div>
</div>
</section>
<section id="case-study---landing-page-ab-test" class="level3">
<h3 class="anchored" data-anchor-id="case-study---landing-page-ab-test">Case study - Landing page A/B test</h3>
<p>You are working for a cosmetics company. The company is researching the amount of time the customers spent on its website. Your team leader ask you to conduct a A/B test to determine if changing the background color of the landing page from grey to green has any effect on the average time spent on the page.</p>
<p>You randomly select two groups of users. The first group visits the gray landing page named version A. The second group visits the green landing page named version B.</p>
<p>Below are the data you collected:</p>
<table class="caption-top table">
<caption>Version A VS Version B</caption>
<thead>
<tr class="header">
<th></th>
<th>Version A</th>
<th>Version B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Landing page color</td>
<td>Grey</td>
<td>Green</td>
</tr>
<tr class="even">
<td>Sample size</td>
<td>40</td>
<td>38</td>
</tr>
<tr class="odd">
<td>Average time spent</td>
<td>300 seconds</td>
<td>305 seconds</td>
</tr>
<tr class="even">
<td>Standard deviation</td>
<td>18.5 seconds</td>
<td>16.7 seconds</td>
</tr>
</tbody>
</table>
<p><strong>Hypothesis</strong></p>
<ul>
<li>Null: There is no difference in the mean time spent on version A and version B</li>
<li>Alternative: There is a difference in the mean time spent on version A and version B</li>
<li>Significant level: 5%</li>
<li>P value: The probability of observing a difference in your sample means as or more extreme (5 seconds) than the difference observed when the null hypothesis is true</li>
</ul>
<p><strong>Calculation</strong></p>
<p><span class="math display">\[t = \frac{(\bar{x}_1 - \bar{x}_2)}{\sqrt{({\frac{s^2_1}{n_1} + \frac{s^2_2}{n_2}})}}\]</span></p>
<ul>
<li>x̄ = sample mean</li>
<li>s = sample standard deviation</li>
<li>n = sample size</li>
<li>s^2/n = variance of the sample mean</li>
</ul>
<p><span class="math display">\[t = \frac{(300 - 305)}{\sqrt{({\frac{18.5^2}{40} + \frac{16.7^2}{38}})}}\]</span></p>
<div id="50b8acdf" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>x1 <span class="op">=</span> <span class="dv">300</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>x2 <span class="op">=</span> <span class="dv">305</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>s1 <span class="op">=</span> <span class="fl">18.5</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>s2 <span class="op">=</span> <span class="fl">16.7</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>n1 <span class="op">=</span> <span class="dv">40</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>n2 <span class="op">=</span> <span class="dv">38</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> (x1<span class="op">-</span>x2)<span class="op">/</span>math.sqrt(s1<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n1 <span class="op">+</span> s2<span class="op">**</span><span class="dv">2</span><span class="op">/</span>n2)</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'T-score: </span><span class="sc">{</span>t<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>T-score: -1.254103693454824</code></pre>
</div>
</div>
<p>T-score: -1.254103693454824</p>
<p>Now you want to get the probability of the red area from the image below, which is lower than -1.2541 and greater than 1.2541</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/two_tails_test_p_value.png" class="img-fluid figure-img"></p>
<figcaption>Two-tail test p-value</figcaption>
</figure>
</div>
<div id="d2de54da" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Given t-score and degrees of freedom</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>t_score <span class="op">=</span> <span class="op">-</span><span class="fl">1.2541</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> <span class="dv">40</span><span class="op">+</span><span class="dv">38</span><span class="op">-</span><span class="dv">2</span>  <span class="co"># degrees of freedom</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-tailed test p-value</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>p_value_two_tailed_t <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> t.cdf(<span class="bu">abs</span>(t_score), df))</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Two-tailed p-value (t-test):"</span>, p_value_two_tailed_t)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Two-tailed p-value (t-test): 0.21364931373347917</code></pre>
</div>
</div>
<p>P-value = 0.2136 or 21.36%</p>
<p>While p-value (21.36%) &gt; significant level (5%), we fail to reject the null hypothesis, and conclude there is no statistically significant differece between the two mean.</p>
</section>
</section>
<section id="z-test-for-proportion" class="level2">
<h2 class="anchored" data-anchor-id="z-test-for-proportion">Z-test for proportion</h2>
<p>We use z-test for proportion as t-test does not apply to proportion for technical reasons.</p>
<p>Z-test for proportion can be used to compare:</p>
<ul>
<li>Defects among manufacturing products on two assembly lines</li>
<li>Side effects to a new medicine for two trial groups</li>
<li>Support for new law among voters in two disctricts</li>
</ul>
<section id="two-tail-z-test-for-proportion-case-study---customer-satisfaction" class="level3">
<h3 class="anchored" data-anchor-id="two-tail-z-test-for-proportion-case-study---customer-satisfaction">Two tail z-test for proportion case study - Customer satisfaction</h3>
<p>Suppose the company claims that 80% of its customers are satisfied with their shopping experience. To test this claim, you survey a random sample of 100 customers. According to the survey, 73% of customers say they are satisfied. Based on the survey data, you conduct a z-test to evaluate the claim that 80% of customers are satisfied.</p>
<p><strong>Hypothesis</strong></p>
<ul>
<li>Null: P = 0.80 (the proportion of satisfied customers equals 80%)</li>
<li>Alternative: P ≠ 0.80 (the proportion of satisfied customers does not equal 80%)</li>
<li>Significant level: 5%</li>
</ul>
<p><strong>Z-score for proportion in hypothesis teseting</strong> <span class="math display">\[Z = \frac{\hat{P}-P}{\sqrt{\frac{{P}(1-{P})}{n}}}\]</span></p>
<div id="69a76a25" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>sample_mean <span class="op">=</span> <span class="fl">0.73</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>pop_mean <span class="op">=</span> <span class="fl">0.80</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>sample_size <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>z_score <span class="op">=</span> (sample_mean<span class="op">-</span>pop_mean)<span class="op">/</span>math.sqrt(pop_mean<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>pop_mean)<span class="op">/</span>sample_size)</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Z-score: </span><span class="sc">{</span>z_score<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-tailed test p-value</span></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>p_value_two_tailed <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> norm.cdf(<span class="bu">abs</span>(z_score)))</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Two-tailed p-value:"</span>, p_value_two_tailed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z-score: -1.7500000000000016
Two-tailed p-value: 0.080118313727634</code></pre>
</div>
</div>
<p>P-value = 0.08</p>
<p>As P-value &gt; significant level, you failed to reject the null hypothesis.</p>
<p>Note that the p-value of 0.08 does not mean there is an 8% probability that the sample proportion is 0.80. Instead, it means there is an 8% probability of observing a sample proportion as extreme as 0.73 or more extreme, given that the true population proportion is 0.80.</p>
<p>To put it in simple term, the p-value answers the question: “If the true population proportion is 0.80, what is the probability of observing a sample proportion as different from 0.80 as 0.73 is?”</p>
</section>
<section id="two-sample-z-test-for-proportion-case-study---employee-satisfaction" class="level3">
<h3 class="anchored" data-anchor-id="two-sample-z-test-for-proportion-case-study---employee-satisfaction">Two-sample z-test for proportion case study - Employee satisfaction</h3>
<p>Let’s say the HR team of an international company conducted an employee satisfaction survey for their London and Beijing office. Both has a sample size of 50. The satisfaction rate of the London office is 67%, Beijing is 57%. We want to find out if the 10% difference is due to chance.</p>
<p><strong>Hypothesis</strong></p>
<ul>
<li>Null (H0): There is no difference in the proportion of the satisfied employees in London and Beijing</li>
<li>Alternative (Ha): There is a difference in the proportion of the satisfied employees in London and Beijing</li>
<li>Significant level: 5%</li>
<li>P-value: The probability of observing a difference in your sample proportion as or more extreme than the difference observed when the null hypothesis is true</li>
</ul>
<p>In this case, we will reject the null hypothesis when p-value &lt; 5%.</p>
<p><strong>Z-score for two sample proportion</strong> <span class="math display">\[Z=\frac{\hat{p_1}-\hat{p_2}}{\sqrt{\hat{p_0}(1-\hat{p_0})(\frac{1}{n_1}+\frac{1}{n_2})}}\]</span></p>
<p><span class="math display">\[\hat{p_1} = \text{Sample proportion of the 1st group}\]</span> <span class="math display">\[\hat{p_2} = \text{Sample proportion of the 2nd group}\]</span></p>
<p><span class="math display">\[n_1 = \text{Sample size of the 1st group}\]</span> <span class="math display">\[n_2 = \text{Sample size of the 2nd group}\]</span> <span class="math display">\[\hat{p_0} = \text{Pooled proportion (weighted average of the two samples)}\]</span> <span class="math display">\[\text{Pooled proportion} = \frac{x_1+x_2}{n_1+n_2}\]</span> <span class="math display">\[x_1 = \text{Number of success in sample 1}\]</span> <span class="math display">\[x_2 = \text{Number of success in sample 2}\]</span></p>
<div id="288372df" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> math</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>p_1 <span class="op">=</span> <span class="fl">0.67</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>p_2 <span class="op">=</span> <span class="fl">0.57</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>p_0 <span class="op">=</span> (<span class="fl">0.67</span><span class="op">+</span><span class="fl">0.57</span>)<span class="op">/</span><span class="dv">2</span></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>x_1 <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>x_2 <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>z <span class="op">=</span> (p_1 <span class="op">-</span> p_2)<span class="op">/</span>math.sqrt(p_0<span class="op">*</span>(<span class="dv">1</span><span class="op">-</span>p_0)<span class="op">*</span>(<span class="dv">1</span><span class="op">/</span>x_1<span class="op">+</span><span class="dv">1</span><span class="op">/</span>x_2))</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Z score: </span><span class="sc">{</span>z<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Two-tailed test p-value</span></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> norm.cdf(<span class="bu">abs</span>(z)))</span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Two-tailed p-value:"</span>, p_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Z score: 1.0301070542879125
Two-tailed p-value: 0.30295975411763143</code></pre>
</div>
</div>
<p>Z score: 1.0301070542879125 Two-tailed p-value: 0.30295975411763143</p>
<p>The probability that thereis a 10% difference between two offices in London and Beijing is 30.3% under the null hypothesis. This is greater than the significant level, therefore we failed to reject the null hypothesis, and concluded that there is no statistical significant in the percentage difference between Beijing and London.</p>
</section>
</section>
</section>
<section id="linear-regression" class="level1">
<h1>Linear regression</h1>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">Simple linear regression</h2>
<p>Linear regression model explore how one or multiple independent variable impact the dependent variable.</p>
<p><strong>Equation</strong> <span class="math display">\[Y = \text{intercept} + \text{slope}*X\]</span></p>
<p>Or it can be written as</p>
<p><span class="math display">\[\mu_{y|x}=\beta_0 + \beta_1 * X\]</span></p>
<p>It’s not always possible to get all the x and y variables in a population. For example if you want to evaluate the impact of number of social media followers against book sales, you can’t get all author in the world for your linear regression model. This is when we use a sample of the population to build the regression model. (estimate of the paramaters). To distinguish the differences, the equation has a hat on the estimate parameters.</p>
<p><span class="math display">\[
\hat{y} = \hat{\beta_0} + \hat{\beta_1} x
\]</span></p>
<p><strong>Independent variable (x)</strong> A variable that explains trends in the dependent variable, also referred to as an explanatory or predictor variable.</p>
<p><strong>Dependent variable (y)</strong> The variable a given model estimates, also referred to as a response or outcome variable.</p>
<p><strong>Slope</strong> The amount that y increases or decreases per one-unit increase of x.</p>
<p><strong>Intercept</strong> The value of y when x equals 0.</p>
<p><strong>Correlation</strong> Describes linear relationships between variables (positive/negative).</p>
<p><strong>Linear regression coefficients</strong> The B-hat shown in the estimated formula are known as regression coefficients. A common way to caculate it is Ordinary Least Squares Estimation (OLS).</p>
<section id="best-fitted-line" class="level3">
<h3 class="anchored" data-anchor-id="best-fitted-line">Best fitted line</h3>
<p>In a simple linear regression model, we want to find the best fitted line, which is the line that fits the data best by minimizing some loss function or error.</p>
<p>There are a few key components associated with this concept.</p>
<p><strong>Error</strong></p>
<p>Some differences between the data we have, the observed values and the predicted value generated by a given model.</p>
<p><strong>Predicted Value</strong> The estimated Y values for each X caculated by a model.</p>
<p><strong>Residual</strong> The difference between observed or actual values and the predicted values of the regression line. We can calculate the residual for each data point. It’s important to note that the sum of residuals in always equal to 0 for <strong>OLS (Oridnary Least Squares)estimators</strong>. This is not always true for other estimators.</p>
<p>The equation for residual is: <span class="math display">\[\epsilon_i=y_i - \hat{y_i}\]</span></p>
<p><span class="math display">\[\epsilon = \text{residual}\]</span></p>
<p><span class="math display">\[y_i = \text{observed}\]</span></p>
<p><span class="math display">\[\hat{y_i} = \text{predicted}\]</span></p>
</section>
<section id="sum-of-squared-residuals-ssr" class="level3">
<h3 class="anchored" data-anchor-id="sum-of-squared-residuals-ssr">Sum of Squared Residuals (SSR)</h3>
<p>The sum of the squared differences between each observed value and its associated predicted value. <span class="math display">\[SSR = \sum_{i=1}^{n} ( y_i - \hat{y}_i )^2\]</span></p>
</section>
<section id="oridnary-least-squares-ols" class="level3">
<h3 class="anchored" data-anchor-id="oridnary-least-squares-ols">Oridnary Least Squares (OLS)</h3>
<p>In linear regression, we use OLS to get the best fitted line. OLS is a method that minimizes the error, or the sum of squared residuals to estimate parameters in a linear regression model.</p>
</section>
<section id="correlation-coefficient-r-pearsons-correlation-coefficient" class="level3">
<h3 class="anchored" data-anchor-id="correlation-coefficient-r-pearsons-correlation-coefficient">Correlation coefficient (r, Pearson’s correlation coefficient)</h3>
<p>The correlation coefficient quantifies the strength of the linear relationship between two variables. It always falls in the range of [-1, 1]. When r is negative, there is a negative correlation between the variables: as one increases, the other decreases. When r is positive, there is a positive correlation between the variables: as one increases, so too does the other. When r = 0, there is no linear correlation between the variables.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/correlation_coefficient_1.png" class="img-fluid figure-img"></p>
<figcaption>Correlation coefficient plots</figcaption>
</figure>
</div>
<p>Note that there are cases where one variable might be precisely determined by another—like y=x2 or y=sin(x)—but the value of the linear correlation between X and Y would nonetheless be low or zero because their relationship is non-linear.</p>
<p>However, r only tells you the strength of the linear correlation between the variables; it does not tell you anything about the magnitude of the slope of the relationship between the variables aside from its sign.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/correlation_coefficient_2.png" class="img-fluid figure-img"></p>
<figcaption>Correlation coefficient plots</figcaption>
</figure>
</div>
<p><strong>Equations</strong></p>
<p><span class="math display">\[r = \frac{covariance(X, Y)}{(SD_X)(SD_Y)}\]</span></p>
<p>Where</p>
<p><span class="math display">\[covariance(X, Y) = \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}{n}\]</span></p>
<p><span class="math display">\[\bar{x} = \text{mean of x}\]</span></p>
<p><span class="math display">\[\bar{y} = \text{mean of y}\]</span></p>
<p><strong>The regression equation</strong></p>
<p>Now that you know about r and you better understand the concept of regression, you’re ready to put everything together to find the line of best fit through the data. The formula for this line is known as the regression equation. There are two keys to this step.</p>
<p>The first is:</p>
<p>The mean value of X and the mean value of Y (i.e., point (x̄, ȳ)) will always fall on the regression line.</p>
<p>The second is to understand what r means:</p>
<p>For each increase of one standard deviation in X, there is an expected increase of r standard deviations in Y, on average over X.</p>
<p>In other words, the slope of the regression line is:</p>
<p><span class="math display">\[m=\frac{r(SD y)}{(SD x)}\]</span></p>
<p>This is m in the formula for a line: y = mx + b. The intercept, represented by b, is therefore: b = y - mx. Because you know that point (x̄, ȳ) is always on the regression line, you can plug in the x and y values from this point to calculate the intercept. Here’s an example using the original sample of five students.</p>
<table class="caption-top table">
<caption>Elements in the regression equation</caption>
<thead>
<tr class="header">
<th></th>
<th>Hours studying (X)</th>
<th>Exam grade (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>mean:</td>
<td>5</td>
<td>80</td>
</tr>
<tr class="even">
<td>SD:</td>
<td>2</td>
<td>10</td>
</tr>
<tr class="odd">
<td>r:</td>
<td>0.6</td>
<td></td>
</tr>
</tbody>
</table>
<p>Now we know the r score, we can use it to calculate the slope(m) and the intercept (b):</p>
<p><strong>Slope (m)</strong> <span class="math display">\[m=\frac{r(SD y)}{(SD x)}=\frac{0.6(10)}{2}=3\]</span></p>
<p><strong>Intercept (b)</strong> <span class="math display">\[y=mx+b\]</span> <span class="math display">\[80=3(5)+b\]</span> <span class="math display">\[b=65\]</span></p>
</section>
<section id="model-assumption" class="level3">
<h3 class="anchored" data-anchor-id="model-assumption">Model assumption</h3>
<p><strong>Linearity</strong></p>
<p>Each predictor variable (Xi) is linearly related to the outcome variable (Y). If you plot the X and Y variables into a scatter plot, they should approximately form a striaght line.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="in"># Create pairwise scatterplots of Chinstrap penguins data</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="in">sns.pairplot(chinstrap_penguins)</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Normality</strong></p>
<p>The residuals or errors are normally distributed. You can only check this after the model is built.</p>
<p>The normality assumption focuses on the errors, which can be estimated by the residuals, or the difference between the observed values in the data and the values predicted by the regression model. Once the model has been built, you can either create a QQ-plot to check that the residuals are normally distributed, or create a histogram of the residuals. Whether the assumption is met is up to some level of interpretation.</p>
<p>The <strong>quantile-quantile plot</strong> (<strong>Q-Q plot</strong>) is a graphical tool used to compare two probability distributions by plotting their quantiles against each other. Here’s how Q-Q plots work when assessing the normality of a model’s residuals:</p>
<p><strong>Rank-order the residuals</strong> Sort your n residuals from least to greatest. For each one, calculate what percentage of the data falls at or below this rank. These are the n quantiles of your data.</p>
<p><strong>Compare to a normal distribution</strong> Divide a standard normal distribution into n+1 equal areas (i.e., slice it n times). If the residuals are normally distributed, the quantile of each residual (i.e., what percentage of the data falls below each ranked residual) will align closely with the corresponding z-scores of each of the n cuts on the standard normal distribution (these can be found in a normal z-score table or, more commonly, using statistical software).</p>
<p><strong>Construct a plot</strong> A Q-Q plot has the known quantile values of a standard normal distribution along its x-axis and the rank-ordered residual values on its y-axis. If the residuals are normally distributed, the quantile values of the residuals will correspond with those of the standardized normal distribution, and both will increase linearly. If you first standardize your residuals (convert to z-scores by subtracting the mean and dividing by the standard deviation), the two axes will be on identical scales, and, if the residuals are indeed normally distributed, the line will be at a 45° angle. However, standardizing the residuals is not a requirement of a Q-Q plot. In either case, if the resulting plot is not linear, the residuals are not normally distributed.</p>
<p>Below are Q-Q plots showing different types of distribution:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/qqplot.png" class="img-fluid figure-img"></p>
<figcaption>Q-Q plot examples</figcaption>
</figure>
</div>
<p>After you calculated the residuals from a linear regression model, you can use the statsmodel to directly plot a Q-Q plot.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="in">import statsmodels.api as sm</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="in">import matplotlib.pyplot as plt</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="in">residuals = model.resid # the residual calculated from a model</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="in">fig = sm.qqplot(</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="in">    residuals, </span></span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="in">    line = 's' # Standardized Line: this adds a line that passes through the mean of the data and has a slope equal to the standard deviation of the data. It accounts for the specific scale of the sample data. If the data is not standardized (i.e., not converted to z-scores), this line helps compare the data's actual scale to the expected normal distribution's scale. </span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="in">    )</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="in">plt.show()</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Independent observations</strong></p>
<p>Each observation in the dataset is independent.</p>
<p>Whether or not observations are independent is dependent on understanding your data. Asking questions like:</p>
<p>How was the data collected? What does each data point represent? Based on the data collection process, is it likely that the value of one data point impacts the value of another data point?</p>
<p>An objective review of these questions, which would include soliciting insights from others who might notice things you don’t, can help you determine whether or not the independent observations assumption is violated. This in turn will allow you to determine your next steps in working with the dataset at hand.</p>
<p><strong>Homoscedasticity</strong></p>
<p>The variation of the residuals (errors) is constant or similar across the model.</p>
<p>Like the normality assumption, the homoscedasticity assumption concerns the residuals of a model, so it can only be evaluated after a regression model has already been constructed. A scatterplot of the fitted values (i.e., the model’s predicted Y values) versus the residuals can help determine whether the homoscedasticity assumption is violated.</p>
<p>In a homoscedastic model:</p>
<p>The residuals should be randomly scattered around zero with no clear pattern (e.g., no funnel shape or systematic variation).</p>
<p>There should not be a visible trend or increasing spread as the fitted values increase.</p>
<p>To determine if the assumption is satisfied: <strong>Random Scatter</strong>: If the points are randomly distributed around the horizontal line (y = 0), with no discernible patterns or increasing spread, then homoscedasticity is satisfied.</p>
<p><strong>No Funnel Shape</strong>: If the residuals fan out or create a funnel-shaped pattern (narrow at one end, wider at the other), this indicates heteroscedasticity (non-constant variance), meaning the assumption is violated.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="in">import matplotlib.pyplot as plt</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="in">fig = sns.scatterplot(fitted_values, residuals)</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="in">fig.axhline(0)</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="in">fig.set_xlabel("Fitted Values")</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="in">fig.set_ylabel("Residuals")</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="in">plt.show()</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/homoscedasticity.png" class="img-fluid figure-img"></p>
<figcaption>Scatter plot to check the homoscedasticity</figcaption>
</figure>
</div>
<p>In this example plot, the residuals seem to be scattered without a clear pattern, though there is a slight variation in spread toward the middle and ends of the plot. However, it does not seem to exhibit a strong funnel shape or a systematic increase in variance. Based on this, the model likely passes the homoscedasticity assumption.</p>
<p><strong>Note on errors and residuals</strong></p>
<p>The terms “errors” and “residuals” sometimes used interchangeably in connection with regression. In actuality, there is a difference:</p>
<p><strong>Residuals</strong> are the difference between the predicted and observed values. You can calculate residuals after you build a regression model by subtracting the predicted values from the observed values. <strong>Errors</strong> are the natural noise assumed to be in the model. <strong>Residuals</strong> are used to estimate errors when checking the normality and homoscedasticity assumptions of linear regression.</p>
</section>
<section id="use-logarithm-to-transform-unfit-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="use-logarithm-to-transform-unfit-assumptions">Use logarithm to transform unfit assumptions</h3>
<p>Applying a log transformation (natural logarithm) in linear regression can make the data more suitable for a linear model by addressing: - Skewness (right-skewed data) (e.g.&nbsp;income, house price) - Non-linear relationships (exponential or multiplicative relationships) (e.g.&nbsp;biological growth, population growth) - Reducing the impact of outliers. - Stabilizing variance.</p>
<p>The natural logarithm (often denoted as ln), which is the logarithm with base e, where e ≈ 2.718. It is a mathematical function that transforms data by compressing large values more than small ones, which can help in stabilizing variance and linearizing relationships between variables in certain situations.</p>
<p>For y &gt; 0</p>
<p><span class="math display">\[y=e^x\]</span></p>
<p><span class="math display">\[\quad Y_{\text{log}} = \ln(Y)\]</span></p>
<p><span class="math display">\[ln(y)=ln(e^x)\]</span></p>
<p>If y = 1000, log(y) = 6.907755278982137</p>
<p>And after you finished the computation using the log variable, you can use expotential function to transform it back. (It may be slighly difference due to rounding)</p>
<div id="19e5a431" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>y<span class="op">=</span><span class="dv">1000</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>log_y <span class="op">=</span> np.log(y)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(log_y)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>reverse_log_y <span class="op">=</span> np.exp(log_y)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(reverse_log_y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>6.907755278982137
999.9999999999998</code></pre>
</div>
</div>
<p>In the context of a pandas dataframe, you can use the <code>apply</code> function to tranform the data in a column:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{python}</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="in">data['Income_1'] = data['LogIncome'].apply(np.exp)</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="in">data['LogIncome_1'] = data['Income'].apply(np.log)</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="fixing-other-unfit-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="fixing-other-unfit-assumptions">Fixing other unfit assumptions</h3>
<p><strong>Left-Skewed Distributions</strong> For left-skewed distributions (where the tail is on the left), log transformation is generally not used. Instead, transformations like the square or cube may be applied to “stretch” smaller values and reduce the skewness. For left-skewed data, transformations such as square root or inverse are more appropriate.</p>
<p><strong>Zero or negative values</strong> Logarithms can’t be applied to zero or negative values, so data with such values need to be handled differently (for example, adding a small constant to avoid issues).</p>
<p><strong>Homoscedasticity</strong> Define a different outcome variable. If you are interested in understanding how a city’s population correlates with the number of restaurants in a city, you know that some cities are much more populous than others. You can then redefine the outcome variable as the ratio of population to restaurants.</p>
<p><strong>Independent observations</strong> Take just a subset of the available data.</p>
<p>If, for example, you are conducting a survey and get responses from people in the same household, their responses may be correlated. You can correct for this by just keeping the data of one person in each household.</p>
<p>Another example is if you are collecting data over a time period. Let’s say you are researching data on bike rentals. If you collect your data every 15 minutes, the number of bikes rented out at 8:00 a.m. might correlate with the number of bikes rented out at 8:15 a.m. But, perhaps the number of bikes rented out is independent if the data is taken once every 2 hours, instead of once every 15 minutes.</p>
</section>
<section id="run-a-simple-linear-regression-model-in-python-with-the-ols-method" class="level3">
<h3 class="anchored" data-anchor-id="run-a-simple-linear-regression-model-in-python-with-the-ols-method">Run a simple linear regression model in Python with the OLS method</h3>
<div id="2cdeaba6" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Import packages</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> statsmodels.formula.api <span class="im">import</span> ols</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Load dataset</span></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a>penguins <span class="op">=</span> sns.load_dataset(<span class="st">"penguins"</span>)</span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Data cleaning</span></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>penguins_sub <span class="op">=</span> penguins[penguins[<span class="st">"species"</span>] <span class="op">!=</span> <span class="st">"Chinstrap"</span>]</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>penguins_final <span class="op">=</span> penguins_sub.dropna()</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>penguins_final.reset_index(inplace<span class="op">=</span><span class="va">True</span>, drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Check assumptions</span></span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>sns.pairplot(penguins_final)</span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Model construction</span></span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a><span class="co">## Subset Data</span></span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>ols_data <span class="op">=</span> penguins_final[[<span class="st">"bill_length_mm"</span>, <span class="st">"body_mass_g"</span>]]</span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a><span class="co">## Write out formula ("y ~ x")</span></span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>ols_formula <span class="op">=</span> <span class="st">"body_mass_g ~ bill_length_mm"</span></span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a><span class="co">## Build OLS, fit model to data</span></span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>OLS <span class="op">=</span> ols(formula <span class="op">=</span> ols_formula, data <span class="op">=</span> ols_data)</span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> OLS.fit()</span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Model Summary'</span>)</span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span>
<span id="cb61-32"><a href="#cb61-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-33"><a href="#cb61-33" aria-hidden="true" tabindex="-1"></a><span class="co"># coef of y = intercept = b</span></span>
<span id="cb61-34"><a href="#cb61-34" aria-hidden="true" tabindex="-1"></a><span class="co"># coef of x = slope = m</span></span>
<span id="cb61-35"><a href="#cb61-35" aria-hidden="true" tabindex="-1"></a><span class="co"># y = mx + b</span></span>
<span id="cb61-36"><a href="#cb61-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-37"><a href="#cb61-37" aria-hidden="true" tabindex="-1"></a>sns.regplot(x <span class="op">=</span> <span class="st">"bill_length_mm"</span>, y <span class="op">=</span> <span class="st">"body_mass_g"</span>, data <span class="op">=</span> ols_data)</span>
<span id="cb61-38"><a href="#cb61-38" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb61-39"><a href="#cb61-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-40"><a href="#cb61-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Check assumptions again</span></span>
<span id="cb61-41"><a href="#cb61-41" aria-hidden="true" tabindex="-1"></a><span class="co">## Get residuals and precitions from the model</span></span>
<span id="cb61-42"><a href="#cb61-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-43"><a href="#cb61-43" aria-hidden="true" tabindex="-1"></a><span class="co"># Subset X variable</span></span>
<span id="cb61-44"><a href="#cb61-44" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> ols_data[<span class="st">"bill_length_mm"</span>]</span>
<span id="cb61-45"><a href="#cb61-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-46"><a href="#cb61-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Get predictions from model</span></span>
<span id="cb61-47"><a href="#cb61-47" aria-hidden="true" tabindex="-1"></a>fitted_values <span class="op">=</span> model.predict(X)</span>
<span id="cb61-48"><a href="#cb61-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-49"><a href="#cb61-49" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate residuals</span></span>
<span id="cb61-50"><a href="#cb61-50" aria-hidden="true" tabindex="-1"></a>residuals <span class="op">=</span> model.resid</span>
<span id="cb61-51"><a href="#cb61-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-52"><a href="#cb61-52" aria-hidden="true" tabindex="-1"></a><span class="co">##Normality</span></span>
<span id="cb61-53"><a href="#cb61-53" aria-hidden="true" tabindex="-1"></a><span class="co">### histogram</span></span>
<span id="cb61-54"><a href="#cb61-54" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> sns.histplot(residuals)</span>
<span id="cb61-55"><a href="#cb61-55" aria-hidden="true" tabindex="-1"></a>fig.set_xlabel(<span class="st">"Residual Value"</span>)</span>
<span id="cb61-56"><a href="#cb61-56" aria-hidden="true" tabindex="-1"></a>fig.set_title(<span class="st">"Histogram of Residuals"</span>)</span>
<span id="cb61-57"><a href="#cb61-57" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb61-58"><a href="#cb61-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-59"><a href="#cb61-59" aria-hidden="true" tabindex="-1"></a><span class="co">## QQ plot</span></span>
<span id="cb61-60"><a href="#cb61-60" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> sm.qqplot(model.resid, line <span class="op">=</span> <span class="st">'s'</span>)</span>
<span id="cb61-61"><a href="#cb61-61" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb61-62"><a href="#cb61-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-63"><a href="#cb61-63" aria-hidden="true" tabindex="-1"></a><span class="co">##Homoscedasticity</span></span>
<span id="cb61-64"><a href="#cb61-64" aria-hidden="true" tabindex="-1"></a><span class="co">### the fitted value is the dependent varaible according to independent variable. Get the y according to the value of x, that's why there was a line (fitted_values = model.predict(X))</span></span>
<span id="cb61-65"><a href="#cb61-65" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> sns.scatterplot(x<span class="op">=</span>fitted_values, y<span class="op">=</span>residuals)</span>
<span id="cb61-66"><a href="#cb61-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-67"><a href="#cb61-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Add reference line at residuals = 0</span></span>
<span id="cb61-68"><a href="#cb61-68" aria-hidden="true" tabindex="-1"></a>fig.axhline(<span class="dv">0</span>)</span>
<span id="cb61-69"><a href="#cb61-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-70"><a href="#cb61-70" aria-hidden="true" tabindex="-1"></a><span class="co"># Set x-axis and y-axis labels</span></span>
<span id="cb61-71"><a href="#cb61-71" aria-hidden="true" tabindex="-1"></a>fig.set_xlabel(<span class="st">"Fitted Values"</span>)</span>
<span id="cb61-72"><a href="#cb61-72" aria-hidden="true" tabindex="-1"></a>fig.set_ylabel(<span class="st">"Residuals"</span>)</span>
<span id="cb61-73"><a href="#cb61-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-74"><a href="#cb61-74" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the plot</span></span>
<span id="cb61-75"><a href="#cb61-75" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Model Summary
                            OLS Regression Results                            
==============================================================================
Dep. Variable:            body_mass_g   R-squared:                       0.769
Model:                            OLS   Adj. R-squared:                  0.768
Method:                 Least Squares   F-statistic:                     874.3
Date:                Thu, 17 Oct 2024   Prob (F-statistic):           1.33e-85
Time:                        07:08:09   Log-Likelihood:                -1965.8
No. Observations:                 265   AIC:                             3936.
Df Residuals:                     263   BIC:                             3943.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==================================================================================
                     coef    std err          t      P&gt;|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept      -1707.2919    205.640     -8.302      0.000   -2112.202   -1302.382
bill_length_mm   141.1904      4.775     29.569      0.000     131.788     150.592
==============================================================================
Omnibus:                        2.060   Durbin-Watson:                   2.067
Prob(Omnibus):                  0.357   Jarque-Bera (JB):                2.103
Skew:                           0.210   Prob(JB):                        0.349
Kurtosis:                       2.882   Cond. No.                         357.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="stats_files/figure-html/cell-30-output-2.png" width="946" height="947" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="stats_files/figure-html/cell-30-output-3.png" width="585" height="449" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="stats_files/figure-html/cell-30-output-4.png" width="613" height="429" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="stats_files/figure-html/cell-30-output-5.png" width="613" height="429" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="evaluate-the-linear-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="evaluate-the-linear-regression-model">Evaluate the linear regression model</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/OLS_regression_summary.png" class="img-fluid figure-img"></p>
<figcaption>Linear regression model summary from the sns package</figcaption>
</figure>
</div>
<p>P&gt;|t| = the p value associated with the coefficient estimate</p>
<p>[0.025] &amp; [0.975] = a 95% confidence interval around the coefficient estimate</p>
<p>In a linear regression model. You will focus on the above metrics for the independent variable, and less on the dependent varaiable.</p>
<p><strong>P-values</strong></p>
<p>When running regression analysis, you want to know if X is really correlated with y or not. So we do a hypothesis test on the regression results. In regression analysis, for each beta coefficient, we are testing the following set of null and alternative hypotheses:</p>
<p>H0 (null hypothesis): <span class="math display">\[\beta_1=0\]</span></p>
<p>H1 (alternative hypothesis): <span class="math display">\[\beta_1! \neq0\]</span></p>
<p>In our example, because the p-value is less than 0.05, we can reject the null hypothesis that β1 is equal to 0, and state that the coefficient is statistically significant, which means that a difference in bill length of a penguin is truly correlated with a difference in body mass.</p>
<p><strong>Confidence band</strong></p>
<p>The area surrounding the line that descrines the uncertainty around the predicted outcome at every value of X.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/confidence_band.png" class="img-fluid figure-img"></p>
<figcaption>Example of a confidence band within the regplot</figcaption>
</figure>
</div>
<p>Each beta coefficient also has a confidence interval associated with its estimate. A 95% interval means the interval itself has a 95% chance of containing the true parameter value of the coefficient. So there is 5% chance that our confidence interval [131.788, 150.592] does not contain the true value of β1. More precisely, this means that if you were to repeat this experiment many times, 95% of the confidence intervals would contain the true value of β1.</p>
<p>But, since there is uncertainty in both of the estimated beta coefficients, then the estimated y values also have uncertainty. This is where confidence bands become useful.</p>
</section>
</section>
<section id="multiple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-linear-regression">Multiple linear regression</h2>
</section>
<section id="advanced-hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="advanced-hypothesis-testing">Advanced hypothesis testing</h2>
</section>
</section>
<section id="logistic-regression" class="level1">
<h1>Logistic regression</h1>
<p>A technique that models a categorical dependent variable based on one or more independent variables. For example, if leads become subscriber or not, customer renew or not renew. The dependent variable can have two or more possible discrete values.</p>
<p>In the case of logistic regression, the relationship between x and y doesn’t forma straight line.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/logistic_regression.png" class="img-fluid figure-img"></p>
<figcaption>Logistic regression doesn’t form a line.</figcaption>
</figure>
</div>
<p>Therefore we need a different way to model the logistic regression. The key is to get the probability of y equals to 1 given x.</p>
<p><span class="math display">\[\mu_{y|x} = \text{Prob}(Y=1|X)\]</span></p>
<p>An easy way to do it would be sum all binary y (0 or 1) and devide by the total count.</p>
<p>However, you would want to link this equation to a regression equation with a formula.</p>
<p><strong>The link function</strong></p>
<p>A nonlinear function that connects or links the dependent variable to the independent variables mathematically.</p>
<p><span class="math display">\[g(p)=\beta_0 + \beta_1 * X\]</span></p>
<section id="linear-regression-vs-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-vs-logistic-regression">Linear regression VS Logistic regression</h2>
<table class="caption-top table">
<caption>Linear regression VS Logistic regression</caption>
<colgroup>
<col style="width: 47%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>Linear regression</th>
<th>Logistic regression</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Continious data (e.g.&nbsp;1, 2, 3…)</td>
<td>Categorial data (e.g.&nbsp;subscribed or not)</td>
</tr>
<tr class="even">
<td>Estimate the mean of y</td>
<td>Estimate the probability of an outcome</td>
</tr>
</tbody>
</table>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>